### ISSUE TITLE
problems about building project to Linux 64-bit-Centos Linux 7(Core)

### ISSUE THREAD

**Issue by c2b26** [tobya/DocTo#104]
I want  to build the project to linux enviroment.I don't know pacal language and how to use X,and then I have prepared environment with the help of http://docwiki.embarcadero.com/RADStudio/Rio/en/Linux_Application_Development#Running_PA_Server_on_Linux_machine.But when i change the project to linux Platform , there are problems.Please help me.
![图片](https://user-images.githubusercontent.com/8330150/72043891-5a30b180-32ed-11ea-9e20-3827c9d0b396.png)

Texts:
Cannot resolve unit name 'SysUtils' at line 24 (24:3)
Cannot resolve unit name 'Classes' at line 25 (25:3)
Cannot resolve unit name 'ActiveX' at line 26 (26:3) 
Undeclared identifier 'TStringlist' at line 38 (38:15)
Undeclared identifier 'TStringlist' at line 44 (44:16)
'TStringlist' does not contain a member named 'create' at line 44 (44:28) 
Undeclared identifier 'ParamCount' at line 52 (52:21) 
'TStringlist' does not contain a member named 'Add' at line 54 (54:18) 
Undeclared identifier "ParamStr' at line 54 (54:22)
Undeclared identifier'Colnitialize' at line 57 (57:7) 
Undeclared identifier 'CoUninitialize' at line 73 (73:7) 
'TWordDocConverter' does not contain a member named 'free' at line 75 (75:157) 
'TExcelXLSConverter' does not contain a member named 'Free' at line 76 (76:15)
Undeclared identifier 'Exception' at line 78 (78:17)
Undeclared identifier'ClassName' at line 80 (80:49)
Undeclared identifier 'Message' at line 81 (81:20)
'TStringlist' does not contain a member named 'Free' at line87 (87:15)

**Comment by tobya** [comment]
Hello @c2b26 Thank you for the issue.  I have never tried to build on Linux and I am unsure whether it is possible.

Word and Excel are both windows only applications so I am unsure why you would need to run DocTo on a linux box.

I think DocTo is platform specific and it is not possible to compile on Linux.

**Comment by c2b26** [comment]
@tobya Thanks for your reply!
The reason  why I need to run DocTo on a linux box is that the server of my company  is linux and now I am ordered to convert Word to PDF by my leader.So I need a function that can convert Word to PDF .
Now I am reading your codes,I hava a question that the function of coverting Word format to PDF format is written by your self or used Window api.
If the code use Window api,i think it is problem make not building on a linux box.

**Comment by tobya** [comment]
DocTo uses Word and Excel to do the conversion.  You will need 1 machine with windows installed (can be windows 7,8,10) and a copy of word .  Then DocTo will work. It will not work on Linux.

**Comment by c2b26** [comment]
Thanks for your reply!
Now I know the DocTo can't be builded  on Linux.Perhaps you have other new ideas to make DocTo builded on Linux?
