### ISSUE TITLE
Exiting with Error 400: EOleSysError Access is denied, ProgID: "Word.Application"

### ISSUE THREAD

**Issue by jorgemfm** [tobya/DocTo#106]
Trying to run this throw a Web Application, but I get the error:

`Exiting with Error 400: EOleSysError Access is denied, ProgID: "Word.Application"`

What kind of permissions do I have to configure?

Thank you

**Comment by tobya** [comment]
Hi  - I'm not sure exactly what permissions you will require, but you may need to play around with permissions needed to interact with desktop (since that's what word does)

If you find out post back here.
