### ISSUE TITLE
Newest binary (V1.2) is detected as a Trojan by Microsoft Defender

### ISSUE THREAD

**Issue by nx10** [tobya/DocTo#112]
The newest binary (V1.2) is detected as a Trojan by Microsoft Defender:

Trojan:Win32/Wacatac.C!ml

V1.1 works fine.

![Screenshot](https://user-images.githubusercontent.com/33600480/74940046-2dde7980-53f1-11ea-9166-191302c02bca.png)

Edit: Weird. Now Version 1.1 is being detected as a different Trojan... (Trojan:Win32/Detplock)

**Comment by tobya** [comment]
Hi Thanks

No trojan in the code that I compile, but is this the binary downloaded directly from github?

What is the reference to AWS in your screenshot?  does github use AWS?

**Comment by nx10** [comment]
Yes I downloaded it directly from GitHub, pretty sure GitHub uses AWS.

**Comment by tobya** [comment]
hmmm.  Not sure what to do about that then.  It may be because it makes COM calls into MS Word. 

Let me know if I can help in any other way.

**Comment by nx10** [comment]
Yes probably a false positive. I have never done this myself but it seems you can submit a binary to Microsoft to have it analyzed:

https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by tobya** [comment]
Thanks - I've submitted the file.

**Comment by tobya** [comment]
They said they've removed it from the signature list.

Try this 

Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
