### ISSUE TITLE
DocTo.EXE blocked by Symantec End Point

### ISSUE THREAD

**Issue by ceugenio** [tobya/DocTo#113]
![image](https://user-images.githubusercontent.com/15365719/75891377-faa7db80-5e2f-11ea-930b-7f0570e0dc2e.png)

**Comment by megapro17** [comment]
Same with windows defender

**Comment by tobya** [comment]
Thank you I have submitted it to these scanners, we'll see what happens.

**Comment by elektrotiko** [comment]
Similar happens with F-secure computer protection. Any news?

**Comment by megapro17** [comment]
btw older version works fine

**Comment by elektrotiko** [comment]
> btw older version works fine
Docto had this problem a year ago as well. I pointed this to the author.

**Comment by tobya** [comment]
> btw older version works fine

That's interestnig thansks
