### ISSUE TITLE
DocTo.EXE blocked by Bitdefender antivirus

### ISSUE THREAD

**Issue by NinjaCross** [tobya/DocTo#115]
![image](https://user-images.githubusercontent.com/5829421/76193802-17079780-61e5-11ea-808b-b9062557411b.png)

**Comment by tobya** [comment]
Thanks I'll try and submit to them

**Comment by tobya** [comment]
Can you send me the report, with name of what trojan etc it thinks has been detected.

I will then submit the .exe to bitdefender.

Thanks

**Comment by NinjaCross** [comment]
@tobya I already submitted it to BitDefender :)

**Comment by tobya** [comment]
Brilliant Thanks
