### ISSUE TITLE
open another word document via explorer while converting

### ISSUE THREAD

**Issue by DanielSeges** [tobya/DocTo#116]
I want to convert bunch of doc files to pdf. I run docto.exe, and I want to view/open another documents while conversion. I  double click on another word document for opening but with no sucess. MS Word is opened and closed immediately.

**Comment by tobya** [comment]
This is a side effect of the automated control of word.  There is no easy way to ignore user opened files.

Docto is opening and closing documents and relying on the active document being one that has been opened by docto, so it is going to get confused if you open documents manually also.

I think it is best to wait until your conversion job has finished before using word manually

**Comment by DanielSeges** [comment]
I wrote my own doc to pdf convertor and I know about side effects.  I know that it's not easy to handle it. However Docto seems to be in right direction to solve this issiue. For example docto wil not close word documents opened before running docto - which is great...However waiting until conversion job has finished is not solution for me or for my clients...Thanks for your reply, I have to solve this issue somehow..

**Comment by tobya** [comment]
Thanks for the update.

If you provide further information about EXACTLY what is happening and EXACTLY what it is you would like to happen, in as much details as you can provide, I'll see if I can find a simple solution.

I am always will to take a PR also.

Thanks for using DocTo

**Comment by DanielSeges** [comment]
I have solved this issue, if you are interested, feel free to reach me out

**Comment by tobya** [comment]
@DanielSeges I would be very interested to know how you solved the issue so others can benefit from this information.

**Comment by DanielSeges** [comment]
@tobya - OK, shorthly - I have build CRM system which is capable of mass word document generation.
Documents were created and user can perform various tasks:
He/she can print out selected documents, export do local disk/ftp, or convert to pdf...etc
If user start pdf conversion, he/she needs to wait until conversion is finished.
It takes some time obviously, and user want to utilize his time. Conversion is running, user wants to open some other word document, but word is closed imidiately. What hapend?
(That was not the case for word document opened before conversion)

I had no clue and I started to investigate it. (I want to point out that all free or paid commandline utilities suffered the same issue)

Solution was to investigate processes running on my machine.

I create COM object

C++/Qt code:
auto mainWord = new QAxWidget(this);
mainWord->setControl("Word.Application");

now you can see winword process in the **list of running processes**.

I want to open word and hide it:
word->dynamicCall("Visible", false);

auto doc = word->querySubObject("Documents");

//fullFileName is path to file
doc->dynamicCall("Open(QVariant)", fullFileName);

QAxObject * activeDocument = word->querySubObject("ActiveDocument");
activeDocument->dynamicCall("SaveAs(const QString&, QVariant)", fullFileName + ".pdf", 17);
activeDocument->dynamicCall("Close(boolean)", false);

ok great I can open word, save as pdf and close it.
I am doing this in loop. Winword running on the backround does to job.

**BUT**, if you open another word document (by double clicking on file)
this document is opened by running winword process, and as you noticed 
command: activeDocument->dynamicCall("Close(boolean)", false); will close it
(Basically it will close all documents opened by this particular winword process - and this was tricky to realize it), which is disaster.

How to handle it?
You can create 2 COM objects. Now there are 2 winword processes sitting on the background.
I am going to use the same code as before, but I will use **second** COM object for conversion:
auto word = new QAxWidget(this);
...

I am doing this in loop again. But if user tries to open word document, it is opened by the first winword process. and running activeDocument->dynamicCall("Close(boolean)", false); will not close that document. Which is exactly what we wanted

At the end I have to do some cleanup...

QAxObject * activeDocument =  mainWord->querySubObject("ActiveDocument");
if(!activeDocument)
{
mainWord->dynamicCall("Quit(void)");
mainWord->deleteLater();
}

**Comment by tobya** [comment]
Thanks for the info, glad you got it working.  

This will be useful for others with the same issue.
