### ISSUE TITLE
XLS to XLSX ?

### ISSUE THREAD

**Issue by onlinegill** [tobya/DocTo#117]
Hello, 
can we convert XLS file to XLSX format ? i tried myfile.xlsx" -T xlCSV   and does create myfile.xlsx but not sure its correct idea. when i try -T xXLSX it shows CONFIG ERROR: File Format xlXLSX is invalid, please see help. -h

**Comment by tobya** [comment]
Thanks for the issue.

`xlXLSX`  is not a valid type try `xlOpenXMLWorkbook` or   `xlWorkbookDefault`

Let me know if it works

**Comment by tobya** [comment]
Please fill in about your use case if you are willing in the wiki https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild
