### ISSUE TITLE
Will support pptx?

### ISSUE THREAD

**Issue by coderafei** [tobya/DocTo#119]
it will be nice~

**Comment by tobya** [comment]
Hi @coderafei yes, i actually have a stalled PR that I am planning on merging.  Now that I know there is  an interest I will try to merge.  You can see it here #92

**Comment by tobya** [comment]
Draft Release available with Powerpoint support, please try it out and provide any feedback.

https://github.com/tobya/DocTo/releases/tag/V1.2PPBeta
