### ISSUE TITLE
XLS and PPT conversions to PDF

### ISSUE THREAD

**Issue by cyrduf** [tobya/DocTo#123]
Can you give command line documentation to convert XLS/XLSX->PDF and PPT/PPTX->PDF ?
How to force for XLS conversion to PDF to have landscape/portait sheet to be fit in 1 page ? 
(often xls sheets columns are splitted on several pages when a print to pdf is made)

**Comment by tobya** [comment]
Hello

There are lots of examples here

https://github.com/tobya/DocTo/blob/master/pages/all/index.md

and specific

https://github.com/tobya/DocTo/blob/master/pages/all/ConvertXLSToFilePDF.md

the PPT is something like

 > docto -PP -f 'c:\path\Slides.ppt' -o 'c:\path\slides.PDF' -t ppSaveAsPDF

At the moment there is no way to adjust the fit to 1 page, though I'm happy to take a PR

Thanks for using Docto

**Comment by cyrduf** [comment]
Thank you.
I will use your help examples.

I will try to understand code if I have time later.
