### ISSUE TITLE
Choco install docto producing error, not installing

### ISSUE THREAD

**Issue by whoAmI-cslim** [tobya/DocTo#124]
When I attempt to install docto via chocolatey, I'm getting the following virus detection and checksum error:

"Unhandled Exception: System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at checksum.Program.Main(String[] args)

ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\docto\docto.exe' did not meet 'dc72bb998986400ce37a5f28f8545056179d665052d34ecea90673be64afb1c9b283966f2de87c54adf81819c272a21e0981f784b280e3ecbfe53994ab543981' for checksum type 'sha512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.

The install of docto was NOT successful.

Error while running 'C:\ProgramData\chocolatey\lib\docto\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - docto (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\docto\tools\chocolateyinstall.ps1'.
 See log for details.

Wanted to pass along as it looks like a checksum error that may be causing the issues.

**Comment by whoAmI-cslim** [comment]
Here is the log output
[docto-error.txt](https://github.com/tobya/DocTo/files/4663999/docto-error.txt)

**Comment by tobya** [comment]
Thanks.  Best thing to do in the meantime is to download directlry from Releases https://github.com/tobya/DocTo/releases

**Comment by NikNakk** [comment]
I've had the same issue. But more worryingly, Windows Defender reports this as malware, as do 33/71 scans at VirusTotal. Scanning the URL is fine, but downloading the file and scanning the file reports 33/71 (https://www.virustotal.com/gui/file/291a46bcdaa7306e7dab9230435c798f8cbc5ea60f2e5ef3795005356d2021af/community). I've verified this using a Ubuntu live boot USB stick, so it's not something specific to my Windows machine.

**Comment by tobya** [comment]
Does that mean someone has put malware in the Choco binary or just that it is being detected as malware? 

Maybe I should just delete the choco install?

**Comment by NikNakk** [comment]
I don’t know. Most antivirus software uses heuristics to determine whether something is malware. However, it’s concerning that multiple tools identify the docto.exe as malware. If you built the executable currently in the v1.2 releases assets, the concern would be whether your build machine has a problem.

**Comment by NikNakk** [comment]
@tobya  Did you resolve why VirusTotal is reporting this as Malware?

**Comment by tobya** [comment]
No, I'm afraid I dont have the resources to check these.

Is this happening with Choco? 

Do you get the same problem if you download from github?

**Comment by NikNakk** [comment]
Yes, directly from GitHub

1. Download docto.exe from https://github.com/tobya/DocTo/releases/tag/V1.2
2. Upload to https://www.virustotal.com

Similar results are seen with the v1.2PPBeta. For v1.03, only a single antivirus program detects it as possible malware based on a heuristic.
