### ISSUE TITLE
Update Multi files (Powerpoint)

### ISSUE THREAD

**Issue by kk12837** [tobya/DocTo#127]
Hi,

The os system is Windows Server 2012 R2 Standard

docto version:
DocTo Version:1.2.26.49.b.pp
OfficeApp Version:15
Source: https://github.com/tobya/DocTo/

I ran the following command in windows server. Ant there are 1 powerpoint file in the directory.

C:\Users\eladmin>

C:\Project\nsw\docto.exe -PP -f \\10.100.28.24\nswv\input\pptx\ -O \\10.100.28.24\nswv\output\pptx\ -OX pdf -t ppSaveAsPDF -L 1 -R true

however, it returns

Ready to Execute
Executing Conversion ...
FileToConvert:\\10.100.28.24\nswv\input\pptx\
OutputFile:\\10.100.28.24\nswv\intput\pptx\.pdf
Ext32
*******************************************
Error: EOleException  The filename, directory name, or volume label syntax is in
correct
*******************************************
Error: Exiting with Error Code : 220

[20200617 17:21:53 -]: Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 11
[20200617 17:21:53 -]: Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 11
Converter:MS Powerpoint
Log Level Set To:10
Loading Configuration...
Parameter Count is 11
Input File is: \\10.100.28.24\nswv\input\pptx\
Output directory: \\10.100.28.24\nswv\intput\pptx\
Type Integer is: 32
Log Level Set To:10
File List

Current Directory: C:\Users\eladmin
Ready to Execute
Executing Conversion ...
FileToConvert:\\10.100.28.24\nswv\input\pptx\
OutputFile:\\10.100.28.24\nswv\intput\pptx\.pdf
Ext32
*******************************************
Error: EOleException  The filename, directory name, or volume label syntax is in
correct
*******************************************
Error: Exiting with Error Code : 220

Did anyone has the same experience?

Thanks

Keith

**Comment by tobya** [comment]
I'll take alook.  It doesnt seem to be finding files.  It may only be looking for ppt not pptx files.

Can you try with a ppt file and see if it works.
I can update if that is the problem.

Thank you for using docto

**Comment by kk12837** [comment]
> I'll take alook. It doesnt seem to be finding files. It may only be looking for ppt not pptx files.
> 
> Can you try with a ppt file and see if it works.
> I can update if that is the problem.
> 
> Thank you for using docto

**Comment by kk12837** [comment]
I tested on the docx dir, it has the same result. It could not find the docx files, but it is able to find doc files.

The os system is Windows Server 2012 R2 Standard

**Comment by kk12837** [comment]
xlsx format has the same problem.

Thanks!

**Comment by tobya** [comment]
Thsi should be a fix.  I havent had time to test it, so let me know if it causes problems.

[docto.zip](https://github.com/tobya/DocTo/files/4798878/docto.zip)

**Comment by tobya** [comment]
I have tested this, it should solve your problem.  I have released it as latest verison https://github.com/tobya/DocTo/releases/tag/1.2.29

**Comment by kk12837** [comment]
It works well! thanks for your help @tobya

**Comment by kk12837** [comment]
hi @tobya 

I experienced error 220 couple of times.

I need to restart my PC to avoid this error. This error pops up if I converted many pptx, like more than 500 ppt. Then it pops error 220.

Is it normal?

Thanks

Keith

**Comment by tobya** [comment]
Hi Keith.

Can you log this as a new issue.?  Its most likely that some files are being left open or not properly closed and so over time are causing issues.  It may also be an issue with PPTX as I havent had a similar issue with XLS or Word .  I'll take a l;ook at the code and see if I can see anything that might be causing it.

Do you get any extra information with the 220 error.  Could you try running next time with verbose logging so that you have log files when you start getting the error?

thanks

**Comment by kk12837** [comment]
Ok, I will try to log it and open a new ticket. Thanks
