### ISSUE TITLE
IIS 10 problem PHP exec, how do I solve the problem?

### ISSUE THREAD

**Issue by achex1986** [tobya/DocTo#129]
Hello everyone, tell me how to solve the problem on IIS 10, in PHP exec command, I have this code
````
<?php

$out = array();
exec('docto -f C:\1.doc -o C:\2.pdf -t wdFormatPDF',$out,$exitcode);
echo "EXEC: ( exitcode : $exitcode )";
print_r($out);`
````

I get this error, tell me what the problem is, why from the cmd command line conversion works, and from PHP exec does not want to work, shows this error

 > EXEC: ( exitcode : 220 )

````
Array
(
    [0] => FileToConvert:C:\1.doc
    [1] => OutputFile:C:\2.pdf
    [2] => Ext17
    [3] => *******************************************
    [4] => Error: EOleException  ?????? ??????? ??????????, ??? ??? ?? ?????? ?? ???? ????????
    [5] => *******************************************
    [6] => Error: Exiting with Error Code : 220
)
````

**Comment by tobya** [comment]
Hi @achex1986 .
Can you run the same query from teh comand line?  Does it work.

- Is the error actually lots of ???? or are you hiding it?
- Can you execute with -l 10 to get verbose logging

> docto -f C:\1.doc -o C:\2.pdf -t wdFormatPDF -L 10

Really we nee dto see what the error is. 

If you get no error when you do it outside php then it is probably to do with user permissions.  Try  using 2 directories that IIS php user has access to.

**Comment by tobya** [comment]
ohh I see on rereading that the command line works.  I woud think it is a user permissions issue or a quoting issue.

i need to see the error though.
