### ISSUE TITLE
Multiple RTF in directory to PDF in another Directory

### ISSUE THREAD

**Issue by camldn** [tobya/DocTo#134]
I want to try and Convert Multiple RTF to PDF from one Directory to a Sub directory.
Im getting error no file match *.DOC*

different commands ive tried
docto -f C:\converted\ -O "C:\converted\done\" -T wdFormatPDF -OX .pdf
docto -WD -f C:\converted\ -O "C:\converted\done\" -T wdFormatPDF -OX .pdf
docto -fx .rtf C:\converted\ -O "C:\converted\done\" -T wdFormatPDF -OX .pdf

How would one run the command for All rtf in one folder to pdf in another?

**Comment by camldn** [comment]
Another Question, would i be able to make a Bat file that calls the Docto and uses the location of the bat file for the converted files?

IE convert.bat containing  'docto -fx .rtf %~dp0 -O "%~dp0\done" -T wdFormatPDF -OX .pdf'

**Comment by tobya** [comment]
Hi 

Thanks for the issue.  I have a feelign at the moment that docto only works with a directory of .doc or .docx files.  It will work with individual .rtf files.

I'll take a look and do a fix

**Comment by tobya** [comment]
Actually I looked at this and the -fx option does this

>  docto.exe -f myinputdir -fx .rtf -o myoutputdir -t wdFormatPDF

The -fx parameter specifies the file extension you want to load in this case *.rtf (dont include *)
