### ISSUE TITLE
Convert rtf file in pdf

### ISSUE THREAD

**Issue by PatrickMercadal** [tobya/DocTo#135]
Hi,

I'm new user with docto and so I try to convert rtf file to pdf. It doesn't work from my end and I have an error in the Windows System Event Viewer.

Impossible de démarrer un serveur DCOM : {000209FF-0000-0000-C000-000000000046}. L’erreur « 2147943712 » s’est produite lors du démarrage de la commande :
C:\Program Files (x86)\Microsoft Office\Root\Office16\WINWORD.EXE /Automation -Embedding

I translate : 
Impossible to start a DCOM server : {000209FF-0000-0000-C000-000000000046}. Error « 2147943712 » occured when starting the command :
C:\Program Files (x86)\Microsoft Office\Root\Office16\WINWORD.EXE /Automation -Embedding

I suppose you could have guessed that I use Office 365. May be it matters.

I check on the website  if there wasn't a ticket for this issue. But I didn't find anything.

I would like to clarify that I start docto by using a command file invoked with Shell_exec in a php file. When I start this command file alone in a windows cmd box it works perfectly.

Thank you very much for your reply.

Patrick

**Comment by tobya** [comment]
Hi Patrick.  Thank you for using Docto.

Usually if it works from Command line but via PHP it is a permissions issue so you need to modify the user that php runs under to see if you can run docto.

**Comment by PatrickMercadal** [comment]
Hi Toby,
Thanks for your reply. You want to say it needs to modify user permissions. I displayed the user that php runs under by the php function get_current_user(). It's this user you want to say ? It displayed the name of my machine not a user name (sense Windows).

**Comment by tobya** [comment]
Yes thats the user you need to check

**Comment by PatrickMercadal** [comment]
Hi Tobby,
User is system. Regarding the error message in the event view Windows it's for the key {000209FF-0000-0000-C000-000000000046}. So from your point of view I must check all the access rights for this user system for this key in the windows registry ?
Regards,
Patrick
