### ISSUE TITLE
I created an NPM wrapper around this awesome tool!

### ISSUE THREAD

**Issue by KerimG** [tobya/DocTo#136]
Hi all, 

we're currently in need of a tool like this. First thing I did was to check NPM whether there are any decent Word to PDF converters but they all delivered subpar outputs, because they would do stuff like first convert the .docx to .html and then use Phantom.js to turn it into .pdf. After that journey, the documents original layout and looks would be way too broken. 

DocTo to the rescue! Since I wanted to integrate into some of our [Profound.js](https://www.npmjs.com/package/profoundjs) projects, I decided to create a [node-wrapper named node-docto](https://www.npmjs.com/package/node-docto) around it. 

Should I add this to the "Using in the Wild" wiki?

**Comment by tobya** [comment]
Hi @KerimG 

That sounds great and thank you for being so enthusiastic about DocTo

Yes please add it to the wiki and I will put a note about your node wrapper on the readme.

**Comment by tobya** [comment]
Can you send me the link to the source and I will link to that also

**Comment by KerimG** [comment]
Hey @tobya, 

you can find the github repo here: https://github.com/KerimG/node-DocTo

I will update the readme and some other things later and add it to the wiki then. 

Thank you.
