### ISSUE TITLE
Batch converting while maintaining path structure

### ISSUE THREAD

**Issue by j-te** [tobya/DocTo#137]
Since we 'must' provide a directory for PDF output, could we have a feature where the PDF is saved with the original folder structure rather than it all be chucked in one folder? I can see this being more powerful with a copy of the original folder structure so we still have to provide an output path.

We could create scripts that repeat the commands but it would be nice to do it in one for sake of a clean log etc. Asking the community before going down this route

**Comment by tobya** [comment]
That is interesting.  I think that happens already.

I have a script that converts lots and lots of Word documents to .txt files (I know not pdf but that doesnt matter)

```` 
DocTo -f "C:\BCSSERVER\RecipeDiff\Recipes_doc\" -o "C:\BCSSERVER\RecipeDiff\recipes_txt" -t wdFormatText -OX .txt --halterror false  -L 5  --writelogfile 
````

The files are in a 2 deep set of folders

>  Docs
         /12
            /123.doc
           /124.doc
           /125.doc
         /13
           /131.doc
           /132.doc
etc

These are converted to

>  txts
         /12
            /123.txt
           /124.txt
           /125.txt
         /13
           /131.txt
           /132.txt

I think it should work for you just with wdFormatPDF.  Also you need the -OX .pdf for output type file extension.

```` 
DocTo -f "C:\BCSSERVER\RecipeDiff\Recipes_doc\" -o "C:\BCSSERVER\RecipeDiff\recipes_txt" -t wdFormatPdf -OX .pdf --halterror false  -L 5  --writelogfile 
````

Let me know if this works for you
