### ISSUE TITLE
Unexpected error on a new server

### ISSUE THREAD

**Issue by chver** [tobya/DocTo#138]
Hi,
I'm configuring a test server and I get some trouble using docto on this new server.
Windows server 2016 / Office 2007
Command line : C:\Docto\docto.exe -F C:\tmp\ZABC-C0007_DIA3.docx -O C:\Tmp\tmppdf2.pdf -Q -T wdFormatPDF -L 10

This command line works well on the prod server, but returns the following error on the test server :
[20201017 10:36:33 -]: Log Level Set To:10
Loading Configuration...
Parameter Count is 9
Input File is: C:\tmp\ZABC-C0007_DIA3.docx
Output file is: C:\Tmp\tmppdf2.pdf
Log Level Set To:10
Current Directory: C:\Users\christophe
Ready to Execute
ExecuteConversion:C:\tmp\ZABC-C0007_DIA3.docx
WordVersion:12.0
WordVersion Major:12
Version < 14 Using Saveas Function
FileToConvert:C:\tmp\ZABC-C0007_DIA3.docx
OutputFile:C:\Tmp\tmppdf2.pdf
Ext17
*******************************************
Error: EOleException  La commande a échoué
*******************************************
Error: Exiting with Error Code : 220

Where could this come from ? Windows security/policies ?

I've tested the command on windows 10/ Office 2007, no problem.

Regards

**Comment by tobya** [comment]
Unfortunately the first version of Word that allowed saving as a pdf was Version14 so you would need to update Word.

I should probably put in a better Error Message

**Comment by tobya** [comment]
Though there is a secret which is that DocTo works perfectly with an unactivated copy of Word

**Comment by enrlc0** [comment]
I just wanna mention, that there is a way to save to pdf from within word 2007. You have to install an AddIn that was originally supplied by MS. I cannot find it on their Website anymore but other trustworthy hosts (chip.de) still offer it for download. Search for "Word 2007 Microsoft Save as PDF or XPS".
The reason why it was not a native word feature in the first place is, that MS did not want to pay Adobe...

Your CLI tool will work perfectly after installing the Addn.

**Comment by chver** [comment]
Thanks for your help. Everything works fine !

**Comment by tobya** [comment]
#141 I'll show in log, but still try to convert.
