### ISSUE TITLE
Convert multiple word docs into one single pdf.

### ISSUE THREAD

**Issue by latinofac** [tobya/DocTo#140]
It would be nice to have a functionality of converting multiple documents into one.
Something like:
docto -F inputfile1.docx inputfile2.docx inputfileN.docx -O outputfile.pdf -t wdFormatPDF

**Comment by latinofac** [comment]
Thank you very much Tobya!
I liked very much your project, mainly because the install and the usage were very easy and simple.
Let me know if you need any help to test new functionalities.
Best regards,Latino
    Em quarta-feira, 21 de outubro de 2020 10:19:24 BRT, github-actions[bot] <notifications@github.com> escreveu:  
 
 


Thank You for the Issue. I will try to get to look at it as soon as I can.

**Comment by tobya** [comment]
This is an interesting idea, but I think it may be out of scope of my use of the project, though if you or someone else wished to add it it could be added.

**Comment by latinofac** [comment]
Hi Toby,
Thank you anyway.I can understand of course.I am not familiar with Delphi, so I am afraid that I won't be able to do it as well.But don't worry, I couldn't find any tool that generates one pdf from many word documents, but I was able to work around the problem merging the pdfs into one using another tool.
But thank you again for your concern.
Best regards,Latino
    Em quarta-feira, 21 de outubro de 2020 10:50:24 BRT, Toby Allen <notifications@github.com> escreveu:  
 
 


This is an interesting idea, but I think it may be out of scope of my use of the project, though if you or someone else wished to add it it could be added.
