### ISSUE TITLE
Error when running docTo with nodejs in service.

### ISSUE THREAD

**Issue by FrancilanJr** [tobya/DocTo#144]
Error when running docTo with nodejs in service.
I don't know what happens when I use it in the development environment of the error I go up to a windows service and the error, says that it did not find the file or the error in the execution of the spawn.

I use nssm to put nodejs into service.

Error example:

Error: EBUSY: resource busy or locked, open 'C:\filesfrs\Homerico.Net\tempfiles ome.docx'

{"error":{"killed":false,"code":220,"signal":null,"cmd":"docto -f C:\\filesfrs\\Homerico.Net\\tempfiles\ ome.docx -O C:\\filesfrs\\Homerico.Net\\tempfiles\ ome.pdf -T wdFormatPDF"},"stderr":""}

**Comment by tobya** [comment]
You appear to have a space between the directory and the file, is this intentional.

> C:\filesfrs\Homerico.Net\tempfiles\ ome.docx

This is most likely causing the issue.

**Comment by FrancilanJr** [comment]
The string when sent to the exe by args has no space but the error response returns with that space. When I run the direct converting function in the exe to a bat file it works normally.
