### ISSUE TITLE
Error: EOleException export failed and error code:220

### ISSUE THREAD

**Issue by a9293340** [tobya/DocTo#145]
CMD:
`"C:\Users\eric hong.CINOHQ2004\Desktop\example\win-unpacked\resources\app.asar.unpacked\node_modules\node-docto\lib\docto.exe" -f "C:\Users\eric hong.CINOHQ2004\Documents\CINO\iCode\myTemplete.docx" -O "C:\Users\eric hong.CINOHQ2004\Documents\CINO\iCode\myTemplete.pdf" -T wdFormatPDF`

But I get this bug:
![擷取](https://user-images.githubusercontent.com/21338083/103198144-986e1900-4922-11eb-8009-2ccee9544d3e.PNG)
That tell me EOleException export failed. How can I do to fixed this bug?

**Comment by tobya** [comment]
Can you please show the out put of 

Docto.exe -v

What version of Word are you using? Does the orig document exist?  Also run the conversion with logging  -L 10

> docto.exe ? ? ?  -L 10

Then post the text here.
