### ISSUE TITLE
IIS 10 problem PHP shell_exec(), user rights problem....?

### ISSUE THREAD

**Issue by wildfandango** [tobya/DocTo#146]
Hello, I have searched a lot about this problem, I have found similar cases but I am not clear about the solution.

CONTEXT 

The APP pool for the IIS site is using LocalSystem (nt authority\system)
php executes (shell_exec) a .BAT file with the following command

> "C:\exe\docto.exe" -F "C:/file/file.docx" -O "C:/file/file.pdf" -T wdFormatPDF -L 10 

the result is as follows:

> [20210128 22:39:30 -]: [DEBUG]  Log Level Set To:10
> Loading ChooseConverter...
> Parameter Count is 8
> Converter:MS Word
> [DEBUG]  Log Level Set To:10
> [INFO]   Loading Configuration...
> [DEBUG]  Parameter Count is 8
> [DEBUG]  Input File is: C:\file\file.docx
> [INFO]   Output file: C:\file\file.pdf
> [DEBUG]  Type Integer is: 17
> [INFO]   Log Level Set To:10
> [DEBUG]  Current Directory: C:\file
> [DEBUG]  Ready to Execute
> [DEBUG]  Executing Conversion ... 
> [INFO]   ExecuteConversion:C:\file\file.docx
> [INFO]   FileToConvert:C:\file\file.docx
> [INFO]   OutputFile:C:\file\file.pdf
> [INFO]   Ext17

*******************************************
Error: EOleException  El comando no está disponible porque no hay ningún documento abierto
Error: EOleException  The command is not available because no document is open (translated by me)
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************

however if I run the same BAT manually from the console it does work

> [20210128 22:47:03 -]: [DEBUG]  Log Level Set To:10
> Loading ChooseConverter...
> Parameter Count is 8
> Converter:MS Word
> [DEBUG]  Log Level Set To:10
> [INFO]   Loading Configuration...
> [DEBUG]  Parameter Count is 8
> [DEBUG]  Input File is: C:\file\file.docx
> [INFO]   Output file: C:\file\file.pdf
> [DEBUG]  Type Integer is: 17
> [INFO]   Log Level Set To:10
> [DEBUG]  Current Directory: C:\file
> [DEBUG]  Ready to Execute
> [DEBUG]  Executing Conversion ... 
> [INFO]   ExecuteConversion:C:\file\file.docx
> [INFO]   File Converted: C:\file\file.pdf

What is the recommended way to run from IIS/PHP to not have problems with permissions? I have tried "almost" everything :(

thanks in advance

**Comment by tobya** [comment]
Thank you for posting the issue.

Can you run from php without it being a .bat file?  There are substantial differntces between running commands directly and throught a .bat file

run the command in php using `exec()`

You may need to play around with " and \" but it should work.  You may also have an issue with the user that php runs under.  You ened to make sure the user can interact with the desktop and has access to needed directories.

**Comment by tobya** [comment]
You can find some more info in https://github.com/tobya/DocTo/issues/57

**Comment by wildfandango** [comment]
I followed your advice along with the indications of [#57](https://github.com/tobya/DocTo/issues/57) (I had already tried it before opening this thread).

I have made the following changes

I no longer call a .CMD file, I call docto.exe directly.
I no longer use shell_exec(), I use exec() directly.

> $cmd = "C:/file/docto.exe -F "C:/file/file.docx" -O "C:/file/file.pdf" -T wdFormatPDF -L 10"
> exec($cmd,$out);

**I receive a different error**

> [20210130 19:02:54 -]: [DEBUG]  Log Level Set To:10
> Loading ChooseConverter...
> Parameter Count is 8
> Converter:MS Word
> [DEBUG]  Log Level Set To:10
> [INFO]   Loading Configuration...
> [DEBUG]  Parameter Count is 8
> [DEBUG]  Input File is: C:\file\file.docx
> [INFO]   Output file: C:\file\file.pdf
> [DEBUG]  Type Integer is: 17
> [INFO]   Log Level Set To:10
> [DEBUG]  Current Directory: C:\
> [DEBUG]  Ready to Execute
> [DEBUG]  Executing Conversion ...
> [INFO]   ExecuteConversion:C:\file\file.docx
> [INFO]   FileToConvert:C:\file\file.docx
> [INFO]   OutputFile:C:\file\file.pdf
> [INFO]   Ext17
> *******************************************
> Error: EOleSysError  La llamada fue rechazada por el destinatario
> Error: EOleSysError  The call was rejected by the recipient (translated by me)
> *******************************************
> *******************************************
> Error: Exiting with Error code : 220
> *******************************************
>

**Comment by tobya** [comment]
@wildfandango I'm afraid it is not something I can help with since I use https://github.com/caddyserver/caddy as our webserver which works very nicely in this instance.  

I think you will find you need to run that php script under a differnte user that has alternative rights. Including Interact with Desktop which word seems to need.  Play around with some options and you might figure it out.  Perhaps lookup search for other utilities that get called by `exec()` in php and how people make them work with IIS.

If you figure it out I would be delighted if you posted here or as a wiki page on this project to help others.

Thanks for using DocTo.
