### ISSUE TITLE
stdout as output option

### ISSUE THREAD

**Issue by Sandoun** [tobya/DocTo#147]
Would be nice to have a standard binary outputstream as option :)

**Comment by tobya** [comment]
im unsure what you mean?  could you explain in more detail?

**Comment by Sandoun** [comment]
Including a datastream of the outputted document instead of a direct save to your disk, so you can catch the piped output (in your preferred language) directly and manipulate it directly without opening the outputted file manually again

**Comment by Sandoun** [comment]
Many commandline tools have these options, like ffmpeg where you can pipe the out like -o - and read from the binary stream directly

**Comment by tobya** [comment]
Oh ok, now I understand.  I could look into that.

**Comment by tobya** [comment]
note for self: https://stackoverflow.com/questions/46293975/delphi-tokyo-for-linux-stream-file-contents-to-stdout-console-output

**Comment by tobya** [comment]
released in 1.04
