### ISSUE TITLE
Relative path fail for destination

### ISSUE THREAD

**Issue by Fentonz** [tobya/DocTo#151]
**Describe the bug**
Fail when converting relative path to absolute path of the destination directory.

**To Reproduce**
Use relative path in destination when converting a directory (in my case directory contained MS word files).

**Expected behavior**
Relative directory is converted to absolute directory automatically and conversion happens.

**Additional context**
Here is a screenshot with all needed information:
![image](https://user-images.githubusercontent.com/47477601/109399155-c20ae700-7949-11eb-8a56-f24d06d4e751.png)

**Comment by tobya** [comment]
Have you tried with windows path identifier eg '.\' rather than './'

> docto.exe -f ".\docs" -o ".\pdfs" -t wdFormatPDF -ox .pdf

**Comment by Fentonz** [comment]
> Have you tried with windows path identifier eg '.' rather than './'
I guess you meant '.\' as you showed in the code below. Doing so still produces the same error.

> Additionally if that doesnt work you could try leaving out the directory altogher for the outoput eg
Same error.

One interesting thing i noticed is that when i specify output to be either
`-o "\pdfs"`
or
`-o "/pdfs"`
it says that files were converted, but the converted files are not in the expected directory. Not sure what is happening here. I dont see the converted files anywhere else...
![image](https://user-images.githubusercontent.com/47477601/109430745-89cbdd00-7a0b-11eb-97fc-322c105ec031.png)

**Comment by tobya** [comment]
I'll takea look and see whats happening

**Comment by kedarbhise** [comment]
I encountered the same issue when trying to use relative paths:

Command Line:
`D:\Draft\Policies>docto -f ".\" -O "..\..\Published\Policies" -T wdFormatPDF  -OX .pdf`

Output:
```
[INFO]   FileToConvert:D:\Draft\Policies\Some Policy.docx
[INFO]   OutputFile:..\..\Published\Policies\Some Policy.pdf
[INFO]   Ext17
*******************************************
Error: EOleException  The directory name isn't valid
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************
```

The tool works correctly when the full path for destination is provided.

**Comment by tobya** [comment]
Thanks @kedarbhise Could you confirm what version you are using

**Comment by kedarbhise** [comment]
> Thanks @kedarbhise Could you confirm what version you are using

V1.3 21 Jun 2020

**Comment by kedarbhise** [comment]
> Try putting a \ a the begining of the relative path for -O and see if that makes any differnce.
> 
> > docto -f "." -O "....\Published\Policies" -T wdFormatPDF -OX .pdf
> 
> If that doesnt work, obviously as a workaround you can use a fully qualified path.

I ended up using the fully qualified path and the results are positive.

Adding a "\" at the beginning of the relative path for -O made no difference, and I see the same error as before:
Command Line:
`D:\Draft\Policies>docto -f ".\" -O "\..\..\Published\Policies" -T wdFormatPDF -OX .pdf`

Output:

```
[INFO]   FileToConvert:D:\Draft\Policies\Some Policy.docx
[INFO]   OutputFile:\..\..\Published\Policies\Some Policy.pdf
[INFO]   Ext17
*******************************************
Error: EOleException  The directory name isn't valid
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************
```

**Comment by tobya** [comment]
I think this issue is fixed in 1.4/1.5 if you download the latest release it should work.

If not please let me know and I will try and track down the issue.

Release https://github.com/tobya/DocTo/releases/tag/V1.5

**Comment by kedarbhise** [comment]
@tobya Tried this with version 1.5.

Some progress - the tool now creates the destination folder, but fails during the file convert.

```
D:\Draft\Policies>docto -f ".\" -O "..\..\Test\Policies" -T wdFormatPDF -OX .pdf
File List
D:\Draft\Policies\Some Policy 1.docx
D:\Draft\Policies\Some Policy 2.docx


[INFO]   Beginning to convert files....
[INFO]   FileToConvert:D:\Draft\Policies\Some Policy 1.docx
[INFO]   OutputFile:..\..\Test\Policies\Some Policy 1.pdf
[INFO]   Ext17
*******************************************
Error: EOleException  The directory name isn't valid
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************
```

**Comment by tobya** [comment]
Thanks for your info.

I have NOW fixed this i think!

You can download here and it will be in next release.

[docto.zip](https://github.com/tobya/DocTo/files/6883489/docto.zip)

**Comment by kedarbhise** [comment]
@tobya 

Thanks for the quick turnaround.

I tested it using the zip file linked in your previous comment, and it is working correctly.

The tool created the target directory in the correct place, and all the output files are created in the correct target folder.

I am happy with the result.

**Comment by tobya** [comment]
@kedarbhise This will be in the V1.6 release, coming today or tomorrow

**Comment by kedarbhise** [comment]
Thanks @tobya 

Looking forward to the new release.
