### ISSUE TITLE
Running the command line from the SSIS task.

### ISSUE THREAD

**Issue by wojt0** [tobya/DocTo#152]
Hello, 
I ran a couple of tests with the tool and it looks like it is working fine when executed straight from the command line. 

Now, I am trying to run the command line as a task in the SSIS scheduler. In theory it should be executed the same way as I would execute via command line. I tried to run this under different accounts, including mine (administrator) but every time I am getting:

```
Error Message
Executed as user: DEV\****. [20210309 09:07:50 -]: [DEBUG]  Log Level Set To:10  Loading ChooseConverter...  Parameter Count is 8  Converter:MS Word  [DEBUG]  Log Level Set To:10  [INFO]   Loading Configuration...  [DEBUG]  Parameter Count is 8  [DEBUG]  Input File is: C:\Docx\SG Template.docx  [INFO]   Output file: C:\Docx\SG Template_pdf.pdf  [DEBUG]  Type Integer is: 17  [INFO]   Log Level Set To:10  [DEBUG]  Current Directory: C:\windows\system32  [DEBUG]  Ready to Execute  [DEBUG]  Executing Conversion ...   [INFO]   ExecuteConversion:C:\Docx\SG Template.docx  [INFO]   FileToConvert:C:\Docx\SG Template.docx  [INFO]   OutputFile:C:\Docx\SG Template_pdf.pdf  [INFO]   Ext17  *******************************************  Error: EOleException  This command is not available because no document is open  *******************************************  *******************************************  Error: Exiting with Error Code : 220  *******************************************.  Process Exit Code 220.  The step failed.
```

I am using office 365 which is installed on my machine.

DocTo Version:1.03.30.54
OfficeApp Version:16
Source: https://github.com/tobya/DocTo/

OS: Windows Server 2016

It seems like there is some kind of permissions issue with the office components. Do you have any ideas how to debug this?
I am getting similar issues when trying to run a PowerShell script which is using the word com object to convert the docs with ssis. When running from the command line, it works fine.

Thanks

**Comment by tobya** [comment]
I have had similar problems before with windows. Take a look at #46 and #57 to see if the solutions offered in the thread will work for you. It seems possibly to be a windows permissions issue.

Let me know if you solve the issue.

**Comment by wojt0** [comment]
Hi,

It works once the C:\Windows\SysWOW64\config\systemprofile\Desktop folder is created.

Thanks!

**Comment by tobya** [comment]
https://github.com/tobya/DocTo/wiki/Fixing-user-rights-issues.
