### ISSUE TITLE
Exception when convert PPT to PDF

### ISSUE THREAD

**Issue by lixinaha** [tobya/DocTo#153]
**Describe the bug**
I use this tool to convert word/ppt to PDF files, but with one PPT file, it will fail sometimes(not everytime).

**To Reproduce**
I call this from Java

**Expected behavior**
The PPT file should be converted to PDF.

**Additional context**
- later 
- later
- OS:  Windows Server 2012

here are the error message i got, but they are in Chinese, i'll translate some into English
problem signature:
  event name:	APPCRASH
  app name:	POWERPNT.EXE
  app version:	16.0.13901.20400
  time stamp:	60704eb9
  error module name:	mso20win32client.dll
  error module version:	0.0.0.0
  error time stamp:	606cd4fe
  exception code:	236490d2
  exception offset:	001cfe83
  OS  ver:	6.3.9600.2.0.0.272.7
  区域设置 ID:	2052
  其他信息 1:	7537
  其他信息 2:	7537725f0268e4cd9549e116a2b50541
  其他信息 3:	cd5b
  其他信息 4:	cd5b15f7a6dd048075f0b778e7cfd530

**Comment by tobya** [comment]
Thanks for the issue.

This looks like a Powerpoint issue to me or a COM issue so I'm not sure what I would be able to do to fix it.  Good to be aware however.
