### ISSUE TITLE
Add Visio to supported applications

### ISSUE THREAD

**Issue by zaphod69** [tobya/DocTo#154]
Can Visio be added to the applications this tool support ?

**Comment by tobya** [comment]
Probably yes, I dont have a version of visio available to test on at the moment, but there shouldnt be an issue. 

I'll see if I get some time to add Visio

Could you provide some example visio documents to test on?

**Comment by zaphod69** [comment]
Sorry for the delay in getting this to you, I've attached a zip file with a sample Vision diagram.

[payslips.zip](https://github.com/tobya/DocTo/files/7642843/payslips.zip)

**Comment by tobya** [comment]
Thanks, I'll take a look when I can. I'll try to add to V1.8

**Comment by tobya** [comment]
I've looked at this.  Visio is a bit differnt to the other apps.  What formats do you want to be able to conver to? pdf or other formats.    PDF is easy others are a bit more convoluted for some reason.

**Comment by tobya** [comment]
@zaphod69 I had added this in a basic fashion. Docto.exe will output .pdf or .xps


````
docto.exe  -VS -f "inputfilesvs/payslips.vsdx" -o "generatedfiles/payslip.pdf" -t visFixedFormatpdf  -l 10
````

you can use 

- visFixedFormatpdf
- visFixedFormatxps

I will link to a download for .exe
