### ISSUE TITLE
`--encoding` is not working when exporting to HTML

### ISSUE THREAD

**Issue by brrd** [tobya/DocTo#155]
First of all, thank you very much for this very useful program.

**Describe the bug**
When exporting a document to HTML with the `--encoding` option, the output file is always in encoded in windows-1252.

This issue looks like this one (someone suggested an answer, but I don't know if it's relevant here): https://stackoverflow.com/q/34026716

**To Reproduce**
Here with UTF-8:

```
docto.exe -F input.rtf -T wdFormatHTML -O test.html -E 65001
```

The same behavior is encountered when running the command from Node.js (https://github.com/brrd/msoconvert).

**Expected behavior**
I would expect the file HTML file to be encoded in UTF-8, and its header to contain this meta:

```html
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
```

Instead, the file is encoded in windows-1252 and the the header contains the following:

```html
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
```

**Additional context**
- Please run the command with `-L 10` to provide verbose logging and paste that into your bug report.  

```
docto.exe -F input.rtf -T wdFormatHTML -O test.html -E 65001 -L 10
[20210528 19:21:26 -]: [DEBUG]  Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 10
Converter:MS Word
[DEBUG]  Log Level Set To:10
[INFO]   Loading Configuration...
[DEBUG]  Parameter Count is 10
[DEBUG]  Input File is: C:\Users\Thomas\Desktop\input.rtf
[DEBUG]  Type Integer is: 8
[INFO]   Output file: C:\Users\Thomas\Desktop\test.html
[INFO]   Log Level Set To:10
[DEBUG]  Current Directory: C:\Users\Thomas\Desktop
[DEBUG]  Ready to Execute
[DEBUG]  Executing Conversion ...
[INFO]   ExecuteConversion:C:\Users\Thomas\Desktop\input.rtf
[DEBUG]  Version >= 14 Using Saveas2 Function
[INFO]   File Converted: C:\Users\Thomas\Desktop\test.html
```

- Please also run docto.exe -v so I can see what version of Docto and Word you are running.

```
docto.exe -v
DocTo Version:1.03.30.54
OfficeApp Version:16
Source: https://github.com/tobya/DocTo/
```

 - What OS: [e.g. Windows Server 2012]

Windows 10 Pro 20H2

**Comment by tobya** [comment]
@brrd Thanks for the thumbs up - always appreciated.

This is really to do with Word.  I did a quick search and couldnt find anything specifically about this issue.  --encoding seems affect the codepage but as you have found out may not change how the conversion to html happens.  

I'll have a look.

**Comment by brrd** [comment]
Thanks for your quick answer! 

I tried to convert from .doc and .docx to html and I get exactly the same result: file encoded in windows 1252 and:

```html
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
```

I hope that it will possible to fix this. I will work in windows-1252 encoding until then.

Do not hesitate if you need any other information.

**Comment by tobya** [comment]
I dont seem to be able to recreate this, when I save documents with docto

when I do 
````batchfile
docto.exe -f "CullohillApplePie - Copy.doc" -o ..\Test1\cullohil.html -t wdFormatHTML -e 65001
````
or
````batchfile
docto.exe -f "CullohillApplePie - Copy.doc" -o ..\Test1\cullohil2.html -t wdFormatHTML

````

Both of them create a word doc with 

````html
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
````

So i think perhaps it is more to do (in the first instance) with settings in word that I'm not overwriting, but I need to know what setting to override.

Can you watch this video and tell me what setting your word has.

https://vimeo.com/556655462/b46c1f8539

**Comment by brrd** [comment]
Your intuition was right, my default export setting was not unicode:

![image](https://user-images.githubusercontent.com/7335302/120096765-986e8100-c12d-11eb-9256-6acbd47b233d.png)

I tried to run docTo again after switching this setting it to "Unicode":

```
docto.exe -F input.doc -T wdFormatHTML -O test.html -E 65001
docto.exe -F input.doc -T wdFormatHTML -O test.html
```

(I tried both)

But I always get the same result: 

```html
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns:st1="urn:schemas-microsoft-com:office:smarttags"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
```

**Comment by brrd** [comment]
Finally I could make it work by checking the box "Always save in default encoding" with "Unicode" selected.

![image](https://user-images.githubusercontent.com/7335302/120097163-462e5f80-c12f-11eb-9278-5a69eef211af.png)

When running docTo again (same commands as above) I could get the expected encoding:

```html
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns:st1="urn:schemas-microsoft-com:office:smarttags"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
```

**Comment by tobya** [comment]
ill play around with some setings and see what i can do

**Comment by tobya** [comment]
I think I have found it.  Seems there is a web encodign as well as a standard encoding .

Please find .zip attached iwth updated binary.  let me know if it works and I'll merge to main.[
[docto.zip](https://github.com/tobya/DocTo/files/6568338/docto.zip)
](url)

**Comment by brrd** [comment]
I can confirm this is working perfectly with this new version!

When running this:

```
docto.exe -F input.doc -T wdFormatHTML -O test.html -E 65001
```

than the output contains as expected:

```html
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
```

with proper UTF-8 encoding.

When running the same command without `-E`, the default encoding is used, which I think is a good behavior.

Thank you very much @tobya for fixing this and for your great reactivity! 

(You maybe want to keep this issue open until the next release is published, so I let you decide when to close it.)

**Comment by tobya** [comment]
Great, I'll merge into next release.

**Comment by tobya** [comment]
Pushed to release. https://github.com/tobya/DocTo/releases/tag/V1.04
