### ISSUE TITLE
Using "wdFormatUnicodeText", the converted txt is still in ANSI format.

### ISSUE THREAD

**Issue by tyf2018** [tobya/DocTo#156]
**Describe the bug**
Using "wdFormatUnicodeText", the converted txt is still in ANSI format.

**To Reproduce**
I am using Total Commander and calling the em command for batch operations, the command code is：
```
[em_DocTo_Word2TXT]
path=%commander_path%
cmd=cmd /c
param=for /F "tokens=*" %%F in ( %L) do (Tools\docto\docto.exe -f "%%F" -T wdFormatUnicodeText -OX .txt)
```

**Expected behavior**
The converted txt file should be in UTF-8 format

**Additional context**
- Please run the command with `-L 10` to provide verbose logging and paste that into your bug report.  
- version of Docto：V1.04
 - What OS: [Windows 10 19043]

**Comment by tobya** [comment]
hmm.  This may be an encoding issue.  i'll take a look
