### ISSUE TITLE
Bug：When docx converts to PDF, there will be an extra horizontal line at the top of the page

### ISSUE THREAD

**Issue by tyf2018** [tobya/DocTo#157]
**Describe the bug**
When docx converts to PDF, there will be an extra horizontal line at the top of the page, which is not what I want. As shown below:
![C_2021 07 01_19 15 18](https://user-images.githubusercontent.com/56342788/124115863-de0dc900-daa0-11eb-99ae-ded62f5ed8eb.jpg)

**To Reproduce**
This is the test file
[Test2021-07-01.docx](https://github.com/tobya/DocTo/files/6747681/Test2021-07-01.docx)

**Expected behavior**
Please prohibit extra horizontal lines at the top of the page.

**Additional context**
Please run the command with -L 10 to provide verbose logging and paste that into your bug report.
version of Docto：V1.04
What OS: [Windows 10 19043]

Thank you！

**Comment by tobya** [comment]
Hello Thank you for your bug report.  The conversion code is all to do with Microsoft Word, so any problem with how the conversion is done (and I'm unsure what the issue is here) is a problem with word which  I dont have anycontrol over. Thanks
