### ISSUE TITLE
Suppress dialog for review comments

### ISSUE THREAD

**Issue by aggies99** [tobya/DocTo#162]
To continue to make the program not require user interaction, need to suppress the warning "The document being saved contains comments. Continue with save?"

**Comment by tobya** [comment]
If you can find out what setting in Word prevents this dialog from being shown i can try to implement it.

**Comment by aggies99** [comment]
I found this page that has some code examples and settings. They seem to make sense for what I am expecting.
https://stackoverflow.com/questions/5083220/how-to-disable-the-document-being-saved-contains-tracked-changes-word-dialog-u

**Comment by tobya** [comment]
Great thanks, I'll see if I can make it work.

**Comment by tobya** [comment]
Could you send me a document that triggers the issue? @aggies99

**Comment by aggies99** [comment]
[Testfile.docx](https://github.com/tobya/DocTo/files/7002558/Testfile.docx)

**Comment by tobya** [comment]
Seems if you set this off on the word level you wont get a prompt dialog from docto.

Word Options->Trust Center->Privacy Options->Uncheck "Warn before printing, saving or sending a file that contains tracked changes or comments"

Do you specifically need it to be unchecked by docto or can you just set it in word on the machine you are running docto on?

**Comment by aggies99** [comment]
I  noticed that is a possibility. We do run many of our scripts locally so
in that case, it would be nice to not have to turn it off for the user.
However, we might for the build machine. I will need to check with the rest
of the team to see what they think.

**Comment by aggies99** [comment]
I did try to update this setting on my personal computer and I am still getting the warning. I am not sure what is going on yet.

**Comment by tobya** [comment]
I have implemented it here, but I think I migth do it differntly in the production code.

This switches off setting , converts the file and switches setting back to how it was.

[docto1-5-b.zip](https://github.com/tobya/DocTo/files/7019648/docto1-5-b.zip)

**Comment by aggies99** [comment]
Quick testing shows success! Thank you for implementing this quickly. To be clear with requirements as you make this production-ready, I would expect that my personal setting is unchanged after the docto application finishes running. If it is set to true when starting, it is still true when done.

**Comment by tobya** [comment]
This is fixed in #168
