### ISSUE TITLE
Parameter for recursivity 

### ISSUE THREAD

**Issue by rom11rom** [tobya/DocTo#163]
First, thanks for this amazong tools. I'm saving so much time thanks to it. 

However, it keep converting files in sub directories. Is there a parameter to stop this behavior and only work in the current directory ? 
Or I'm using a wrong command line ? 

docto -f "c:\..." -o "c:\...." -t wdFormatPDF -OX .pdf

**Comment by tobya** [comment]
Thanks for the issue.  Currently there is no parameter to prevent this, I will look at it.

**Comment by tobya** [comment]
Fixed in main

**Comment by tobya** [comment]
@rom11rom This will be in the next release 1.6 in the next couple of days

**Comment by rom11rom** [comment]
Hi Tobya

Thank you so much for implementing my request, it works very well. 


You're doing a greatt ob
