### ISSUE TITLE
path with "-" caracter

### ISSUE THREAD

**Issue by rom11rom** [tobya/DocTo#164]
**Describe the bug**
command line : docto -f %1 -o %cd% -t wdFormatPDF
error message "CONFIG ERROR: Unknown Switch or Parameter at index 5:-" when using a path with symbol "-" in it. 

*Version**
docto.exe -v
DocTo Version:1.5.34
OfficeApp Version:16
Source: https://github.com/tobya/DocTo/

I would really appreciate if this could be fixed :)

**Comment by rom11rom** [comment]
found the issue myself. 
It was a problem from my batch file, not from your soft.

**Comment by tobya** [comment]
Thanks for the update.
