### ISSUE TITLE
At "Multiple Files and Folders" mode, it stopped at Word's `Show repairs` dialog.

### ISSUE THREAD

**Issue by Honghe** [tobya/DocTo#165]
**Describe the bug**

At "Multiple Files and Folders" mode, it stopped at the following pic, even though running with `--halterror False`.
![image](https://user-images.githubusercontent.com/1092722/137836716-1c0c1d3f-6464-43c1-8a0b-c00de8666876.png)

**To Reproduce**

```
docto -f "C:\Dir with Spaces\FilesToConvert\" -O "C:\DirToOutput" -T wdFormatPDF  -OX .pdf --DoNotOverwrite -X False
```

**Expected behavior**

If there is a problem with some docs, it can skip/pass the docs.

**Additional context**
- Please run the command with `-L 10` to provide verbose logging and paste that into your bug report.  

```
docto -f "C:\Dir with Spaces\FilesToConvert\" -O "C:\DirToOutput" -T wdFormatPDF  -OX .pdf --DoNotOverwrite -X False -L 10
```

```
[20211019 10:56:08 -]: [DEBUG]  Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 13
Converter:MS Word
[DEBUG]  Log Level Set To:10
[INFO]   Loading Configuration...
[DEBUG]  Parameter Count is 13
[DEBUG]  Input File is: C:\Dir with Spaces\FilesToConvert\
[INFO]   Output directory: C:\DirToOutput\
[DEBUG]  Type Integer is: 17
[INFO]   DoNotOverwrite=True
[INFO]   Log Level Set To:10
```
- Please also run docto.exe -v so I can see what version of Docto and Word you are running.

```
DocTo Version:1.5.34
OfficeApp Version:15
```
 - What OS: Windows 10 Pro

**Comment by tobya** [comment]
Hi
If Word wants to pop up dialogs, unforutnatley there isnt much that DocTo can do about it.  In some instances it is possible to set a value somewhere that prevents the pop up but its not always clear where.  if you can find the setting i can look at adding it. 

Can you send me a word document that triggers this issue for testing.

**Comment by tobya** [comment]
Thanks, that's very useful.

I'll try to get a chance to use that instead.
