### ISSUE TITLE
Support for Office 2021

### ISSUE THREAD

**Issue by hrst** [tobya/DocTo#166]
Thanks a lot for this very interesting project! I'm planning to set up a Windows Server for converting DOCX to PDF and wanted to ask whether the new Word from Office 2021 is supported as well? It was just released so I'm wondering whether anyone has tried this out yet. Thanks for any help!

**Comment by tobya** [comment]
I don't see why not. Microsoft is very good at ensuring backwards compatibility 

I don't have a copy so can't check.
