### ISSUE TITLE
Allow saving to PDF/A

### ISSUE THREAD

**Issue by hrst** [tobya/DocTo#167]
Idea for a future version: adding a parameter for saving as PDF/A.

As far as I understood, this could be achieved by allowing to set the following parameter to True:
https://github.com/tobya/DocTo/blob/cc8fb8e9f1a91d7eb3937851043e789f23b46f27/src/WordUtils.pas#L238

This would be highly appreciated!

**Comment by tobya** [comment]
ok thanks. 

What does PDF/A stand for>?

**Comment by hrst** [comment]
@tobya [PDF/A](https://en.wikipedia.org/wiki/PDF/A) is basically a standardized version of PDF and especially interesting when using PDF for archiving purposes. For example, the font (subsets) used in the PDF are embedded into the document, which means it is displayed correctly even if the font is not installed on the system.

The "official" name for the PDF/A standard is ISO 19005-1, hence this name is used as the parameter name by `ExportAsFixedFormat()`, but what is basically does is creating a PDF/A document instead of PDF.

Since Word (and other Office products as well) offers the option to save as PDF/A, it would be awesome to have it in DocTo! Just an idea / feature request of course, I know there might be more important things!

**Comment by tobya** [comment]
ok thanks, I'll add it the next release

**Comment by tobya** [comment]
This will be in the next release v1.6 which should be out this weekend. @hrst
