### ISSUE TITLE
under windows server 2016 64-bit raise error 0xc0000005

### ISSUE THREAD

**Issue by zain84** [tobya/DocTo#173]
DocTo  Version 1.5.34
under windows server 2016 +4-bit while try to run the program its give me this alert message ,  " application was unable to start correctly 0xc0000005 " ,  any help for this issue .

**Comment by tobya** [comment]
This is more than likely an issue to do with your installation of Word.

can you give me details of the command you wnat to run and run it with -L 10

**Comment by tobya** [comment]
Feel free to reopen with more info
