### ISSUE TITLE
error 400 when invoking docTo from IIS/.NET

### ISSUE THREAD

**Issue by luigipavan** [tobya/DocTo#175]
Hi,
I'm getting an error when invoking docTo.exe from IIS.
The same command invoked directly works without any problem.
The executable is hosted in a dedicated directory inside the website stuff.

Here's my log:
[DEBUG]  Log Level Set To:10
Loading ChooseConverter...
Parameter Count is 8
Converter:MS Word
[DEBUG]  Log Level Set To:10
[INFO]   Loading Configuration...
[DEBUG]  Parameter Count is 8
[DEBUG]  Input File is: C:\dati\web\offerlab\temp\SEMPLICE_WEB_LUCE.doc
[INFO]   Output file: C:\dati\web\offerlab\temp\SEMPLICE_WEB_LUCE.pdf
[DEBUG]  Type Integer is: 17
[INFO]   Log Level Set To:10
Exiting with Error 400: EOleSysError
Accesso negato, ProgID: "Word.Application"

Any suggestion ?
Thanks a lot

**Comment by tobya** [comment]
Try these issues.  There is a solution.  the user needs to have rights to allow word to interact with desktop

- #106 
- #35

**Comment by tobya** [comment]
This has all sorts of causes, mainly to do with the rights of the user.  The user that is executing docto for iis will need to have rights to run word and interact with desktop.  Perhaps see if you can find out what permissions are required for IIS to call COM objects.  Let me know if you find a solution.

Some previous issue that might be helpful.
- #57
