### ISSUE TITLE
[Feature Idea/Request] Allow printing to printer

### ISSUE THREAD

**Issue by hrst** [tobya/DocTo#176]
It would be awesome to be able to specify a printer and have DocTo use that printer. My usage scenario is that I have to use a specific PDF printer to generate the PDF.

**Comment by tobya** [comment]
hmmm.  I can look at whether or not this is feasible.  I'm not sure it is.

Word is doing a conversion as an export and not via printing so it is a different process. 

In your use case do you need the PDF to be generated to a specific printer or do you need your word document to be printed to a specific printer?

**Comment by tobya** [comment]
Ok,  I think this is outside the remit of the project, but I'll take a look.

if you do any programming you could probably write a simple script to print out files with your printer driver

vba lets you automate anything with work.

https://docs.microsoft.com/en-us/office/vba/api/word.application.printout
