### ISSUE TITLE
[Feature Idea] Allow setting of WdExportOptimizeFor

### ISSUE THREAD

**Issue by hrst** [tobya/DocTo#177]
Could you maybe kindly add a parameter for the[ WdExportOptimizeFor](https://docs.microsoft.com/en-us/office/vba/api/word.wdexportoptimizefor) flag? This would allow to choose between the two options wdExportOptimizeForOnScreen and wdExportOptimizeForPrint.

**Comment by tobya** [comment]
I'll take a look

**Comment by tobya** [comment]
I implemented it.  I'll include it in the next release.  I was planning on implementing the remaining parameters on the ExportAsFixedFormat function call anyway so this pushed me on.

I have attached a zip with an upated build if you want to try it out.

> --PDF-OptimizeFor forPrint | ForONScreen

I tested it and it produced 2 differnt sized pdf from a complex .docx so I presume its working.  Any feedback would be great.

if you havent already, could you put a little note in the wiki as to how you are using `Docto`? Thanks.

https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild

@hrst

**Comment by tobya** [comment]
[docto.zip](https://github.com/tobya/DocTo/files/8104653/docto.zip)
