### ISSUE TITLE
ppSaveAsPDF thows error

### ISSUE THREAD

**Issue by chross** [tobya/DocTo#188]
Hi!
When converting a pptx file, I'll get the following error
`CONFIG ERROR: File Format ppSaveAsPDF is an invalid Word file extension , please see help. -h`

My command line:
`D:\docto\docto.exe -F D:\temp\95bd6f75528c0b64be1eebb6fede52d974702009.pptx -O D:\temp\ -T ppSaveAsPDF -R true`

I have already tried the -T 32 option, but this file extension is not found
`CONFIG ERROR: File Format 32 is invalid, please see help. -h.  To force use, use -TF`

Using -TF 32, it says file possibly damaged
`Error: EOleException Die Datei ist möglicherweise beschädigt`

However, the file opens fine in PowerPoint.

I'm using PowerPoint 2016 16.0.4266.1001 32bit on a Windows 10 64bit machine.

The output of docto.exe -H PP is
`D:\docto>D:\docto\docto.exe -H PP
Format HELP
DOCTO
Listed below are all Accepted formats that PowerPoint will export to and their associated file extensions:
--
ppSaveAsAddIn=8
ppSaveAsAnimatedGIF=40
ppSaveAsBMP=19
ppSaveAsDefault=11
ppSaveAsEMF=23
ppSaveAsExternalConverter=64000
ppSaveAsGIF=16
ppSaveAsJPG=17
ppSaveAsMetaFile=15
ppSaveAsMP4=39
ppSaveAsOpenDocumentPresentation=35
ppSaveAsOpenXMLAddin=30
ppSaveAsOpenXMLPicturePresentation=36
ppSaveAsOpenXMLPresentation=24
ppSaveAsOpenXMLPresentationMacroEnabled=25
ppSaveAsOpenXMLShow=28
ppSaveAsOpenXMLShowMacroEnabled=29
ppSaveAsOpenXMLTemplate=26
ppSaveAsOpenXMLTemplateMacroEnabled=27
ppSaveAsOpenXMLTheme=31
ppSaveAsPDF=32
ppSaveAsPNG=18
ppSaveAsPresentation=1
ppSaveAsRTF=6
ppSaveAsShow=7
ppSaveAsStrictOpenXMLPresentation=38
ppSaveAsTemplate=5
ppSaveAsTIF=21
ppSaveAsWMV=37
ppSaveAsXMLPresentation=34
ppSaveAsXPS=33`

**Comment by chross** [comment]
My bad! I was missing the -PP and -XL options for Powerpoint and Excel.
However, the file extension .32 for PPTX is a bit strange, when converting to PDF, could this somehow be changed?

**Comment by tobya** [comment]
Thanks for solving it.

Can you log the .32 issue as a seperate bug.  I will fix it.

As a work around you can use -ox .pdf which should work.  This sets the output extension when using an output dir

If that doesnt work you can set the full output filename including .pdf which should work.
