### ISSUE TITLE
'Multiple Files and Folders' If file opened in word convert temporary files 

### ISSUE THREAD

**Issue by mrflusha** [tobya/DocTo#191]
**Describe the bug**
If file opened in word convert temporary files

**To Reproduce**
1. open files in folder with .doc

2. run shell `docto -f "C:\Dir with Spaces\FilesToConvert\" -O "C:\DirToOutput" -T wdFormatPDF  -OX .pdf`
**Actual result**
![temp](https://user-images.githubusercontent.com/46491304/163472801-b422cd23-605b-47bf-94cb-c09c2ea4d670.png)
Temp files converted
**Expected behavior**
File directory w.o. temp files '~'

**Additional context**
Word 2007, win 10 20h2

**Comment by tobya** [comment]
Thank you.  Can you please run it again with -v at the end for verbose logout put and post the entire log 

Do you mean that you have the file open in word when docto is trying to convert the file also?

If so what do you think should be the correct behaviour when this h appens?

**Comment by mrflusha** [comment]
Sorry for my worst English. 
So I will can make this after monday. 
But I mean what, we know temporary .doc files if them opened star from char '~' and we can delete it after convertation. So and may be don't convert it. if files start from '~': pass. 
Weary ty for that utility this is best from all. But that bug,  just a bug. Need to fix it or notnot, your decide. i just noticed this, and report it.

**Comment by tobya** [comment]
Sorry I got confused, -v will not work , you must us -L 10

This will do verbose logging

**Comment by mrflusha** [comment]
idk. but temp files created if MSWORD open any file. If not opened in new folder convert with out '~*'
some log unlikely to help for your....




config:
Word_20220419=12
![path_free](https://user-images.githubusercontent.com/46491304/164077983-8fbf585c-aae0-4d92-9d73-f0a324a94312.png)
![path_free2](https://user-images.githubusercontent.com/46491304/164077986-df93601d-2a05-49b6-9d38-b5558dfd7f53.png)
[l10.log](https://github.com/tobya/DocTo/files/8515846/l10.log)
[v.log](https://github.com/tobya/DocTo/files/8515976/v.log)

**Comment by tobya** [comment]
Ok, Thanks, I'll take a look

**Comment by tobya** [comment]
This should be in next release v15
