### ISSUE TITLE
Disable all alerts

### ISSUE THREAD

**Issue by hade94** [tobya/DocTo#193]
**Describe the bug**
After converting a .docx to pdf this alert shows up. The process does not finish until i close the popup.  This seems like the file is using some kind of office 365 template and it is trying to authenticate against the corperate sharepoint online. The file is converted successfully after not logging in.

**Expected behavior**
There should be an option to disable all alers like --no-alerts

![alert](https://user-images.githubusercontent.com/60658900/170058969-71d78052-3b6a-4ad9-b09a-2359e19e6c17.JPG)

There should be the option to use the property .DisplayAlerts = false in the Word Interop module.

Thanks in advance.

**Comment by tobya** [comment]
It was always a function of word that it popped up alerts.  I had never been able to figure out how to avoid this. 

I will check out displayalerts = false and see if that fixes the issue.  Thanks for finding it.

**Comment by hade94** [comment]
Hi Tobya,

i've tested this behavior in a quick and dirty vbs script with the word com api. 

Unfortunately this doesnt solve the problem. I've moved to libreoffice to convert docx and xlsx to pdf.

Works like charm but without the hassle of word and the windows requirement.

Thanks anyway

**Comment by tobya** [comment]
Thanks for the details.
