### ISSUE TITLE
Some images does not appear in the pdf file

### ISSUE THREAD

**Issue by PierreTav** [tobya/DocTo#194]
Hello,

Here is a .docx sample to reproduce the problem :
[Ticket 700.docx](https://github.com/tobya/DocTo/files/8939783/Ticket.700.docx)
.

The problem does not appear if you open and print de document using "Microsoft Print to PDF" printer.

Have a good day.

Pierre

**Comment by PierreTav** [comment]
When i use : File>Save as>More options>select Type : PDF (*.pdf)>Save
Images appears in the pdf file

**Comment by tobya** [comment]
Ok thanks I'll take a look, could you upload the pdf with the msising images as well as the docx.

**Comment by PierreTav** [comment]
Yes, thank you ! Here it is :
[Ticket 700.pdf](https://github.com/tobya/DocTo/files/8940345/Ticket.700.pdf)

**Comment by tobya** [comment]
Ok thanks.  It's not obvious to me why this should be happening, but I'll take a look.

Can you share the command line you use to generate the pdf?  Perhaps it might be an issue with a compatibility setting or format.

**Comment by PierreTav** [comment]
Hello Tobya,

Did you find something ?

Have a good day,

**Comment by tobya** [comment]
Can you please let me know the details from 

docto -v

I need to know the verison you are using.

What version of Word are you using

**Comment by PierreTav** [comment]
Here it is :
DocTo Version:1.7.36
OfficeApp Version:16
Source: https://github.com/tobya/DocTo/

Word : Version 2205 (build 15225.20288)

**Comment by PierreTav** [comment]
Hello Tobya,

Have you got something ?

Have a nice day,

**Comment by tobya** [comment]
Hello Pierre,  No I'm afraid I do not have time at the moment to look at this, I will let you know when I get some time to look.  In the meantime perhaps you may need to find an alternative solution.  Thank you for trying out DocTo

**Comment by PierreTav** [comment]
Ok i will try to find another. 
DocTo is really good and was working really nicely until this problem appears a few weeks later.
Before changing solution i will try to figure out what's happening.
i tell you if i find an explanation.
Thank you,

**Comment by tobya** [comment]
@PierreTav 


I just tried it on a server I have with Word Version 15 (2013) INSTALLed and it worked fine, so it must be an issue with user permissions / Network etc or Word version 16

Here is the pdf I generated  which seems to have all the images.

[Ticket.700.pdf](https://github.com/tobya/DocTo/files/9011906/Ticket.700.pdf)

Thanks again for trying out DocTo.

**Comment by PierreTav** [comment]
Running from command prompt.
So the problem probably comes from the new version of Word. I will install an older version and try it.
Don't think it's a permission problem because : 
- The problem occur on two differents machines
- Running the command prompt in admin mode don't change anything

**Comment by tobya** [comment]
If you were willing to leave a note about what you or your company is using DocTo for in the wiki, that would be great, thanks.

https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild

**Comment by PierreTav** [comment]
_If you were willing to leave a note about what you or your company is using DocTo for in the wiki, that would be great, thanks._
Done
