### ISSUE TITLE
 docto_64.zip is presenting to Windows 10 Pro as adware/malware

### ISSUE THREAD

**Issue by User59861** [tobya/DocTo#208]
**Describe the bug**
 docto_64.zip is presenting to Windows 10 Pro as adware/malware.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Adware%3AAndroidOS%2FMultiverze&threatid=305121

**To Reproduce**
What code are you calling DocTo from .  Are you using the command line?  Are you calling it from PHP, Ruby, Javascript etc.

I am unzipping docto_64.zip with peazip and defender immediately quarantines.

**Expected behavior**

I expect docto_64.zip to unzip

**Additional context**
- Please run the command with `-L 10` to provide verbose logging and paste that into your bug report.  
- Please also run docto.exe -v so I can see what version of Docto and Word you are running.
 - What OS: [e.g. Windows Server 2012]
- if using in Website, what Webserver do you use.

**Comment by tobya** [comment]
Hello, Yes, it does sometimes. 

I'm afraiid there is very little I can do about it, but if you would like to report it as not malware that woudl be great.

Thank you.

**Comment by cachius** [comment]
For reference, I mentioned docto.exe from the v1.15 zip archive at https://github.com/tobya/DocTo/issues/211#issuecomment-2291395664
