### ISSUE TITLE
Converting Excel file touches last modified file date

### ISSUE THREAD

**Issue by unitycoder** [tobya/DocTo#209]
**Describe the bug**
Converting Excel file touches last modified file date

**To Reproduce**
- check last modified date for document.xlsx
- convert file: docto -XL -f document.xlsx -o documentexcel.pdf -t xlpdf
- check last modified date for document.xlsx (it has been modified)

**Expected behavior**
last modified date should not change (since document is not changed?) 

**Additional context**
if you open the file in Excel manually (and export pdf), last modified date is not changed.

**Comment by tobya** [comment]
Ok, I'll take a look.

**Comment by tobya** [comment]
I have solved this I think.  Can you Try the updated binary at

https://github.com/tobya/DocTo/releases/tag/v1.10

Would you mind lettign me know if this solves your issue.

@unitycoder

**Comment by unitycoder** [comment]
Works, tested both excel and word documents.

Needed this for my workflow where i compare source excel file timestamp,
so that can convert again, if pdf is older than excel file.

thanks!

**Comment by tobya** [comment]
Great.  I'll make release in next few days
