### ISSUE TITLE
Access Denied to IIS/Application pool user while converting .XML to .PDF 

### ISSUE THREAD

**Issue by PortalGuy** [tobya/DocTo#213]
I get Access Denied  while converting .XML to .PDF I get  following for IIS/Application pool use
Error 400: EOleSysError
Access is denied, ProgID: "Word.Application"

When I run the same command (DITTO) as a logged in user I am able to execute the same command successfully without any issue .
Here is the command
docto -f  "G:\faa2\User\Company\404-IFOM-2023-06-11.xml" -o  "G:\faa2\User\Company\404-IFOM-2023-06-11.pdf"  -T wdFormatPDF

Note:
Winword is install
The folder structure has all permissions from root for the IIS/Application pool user 
The same application runs with no issue on other laptop with same software versions
Used Procmon to look at both commands it shows as success executing the docto command unable to drilldown further to see where actually it errors out.

Help is much appreciated

**Comment by tobya** [comment]
This is most likely a permissions issue

see these issues

- https://github.com/tobya/DocTo/issues/57
- https://github.com/tobya/DocTo/issues/175

You need to give the IIS user running docto Interact with desktop permissions

**Comment by PortalGuy** [comment]
@tobya Let me try to provide  IIS user running docto Interact with desktop permissions.

**Comment by PortalGuy** [comment]
1. Since IIS is not running as service don't know how to provide IIS user running docto Interact with desktop permissions.

2. Tried other  suggestions in the post did not help , are there any other suggestions ?

**Comment by PortalGuy** [comment]
@tobya  I have an update , I was able to get it running . 
1 .On the IIS Management Console>> ApplicationPool >> Identity >> I changed the The "IdentityPoolUser" to "LocalService".
2. Restarted IIS 
It worked .
@tobya thank you for your time on this ticket.
