### ISSUE TITLE
Unable to delete multiple files in a directory

### ISSUE THREAD

**Issue by samer9790** [tobya/DocTo#214]
**Describe the bug**
DocTo was unable to delete multiple files when specifying a directory. 

**To Reproduce**
I am using cmd for calling 

this works: 
docto.exe -WD -f F:\docto\123.rtf -o F:\docto\-t wdFormatPDF -R true
because i am specifying the file "123.rtf".

this is not working 
docto.exe -WD -f F:\docto\aaa\ -fx .rtf -o F:\docto\ -t wdFormatPDF -R true
because i am not specifying the file to be deleted

**Expected behavior**
I am expecting the program to delete all ".rtf" files in the directory.

**Comment by tobya** [comment]
I'll take a look and see if I can reproduce.  Should be straightforward to fix if I can.

**Comment by tobya** [comment]
The last release 

- https://github.com/tobya/DocTo/releases/tag/v1.11

has a fix for this issue.

Thanks for using Docto.
