### ISSUE TITLE
Feature Request: Password protected PDF

### ISSUE THREAD

**Issue by mariusnel266** [tobya/DocTo#220]
Can you add password encryption for Word to PDF output please?

**Comment by mariusnel266** [comment]
Password protected pdf - as end result, in other words you convert the doc to a pdf and then save to password protected .pdf document. (Want the PDF to be encrypted/passworded)

**Comment by tobya** [comment]
I'll try and take  alook.

**Comment by tobya** [comment]
https://www.google.com/search?q=word+save+pdf+password+protect&oq=word+save+pdf+password+protect&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRhA0gEINjQ3OWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8

**Comment by tobya** [comment]
I looked at this and seems its not possible.  Microsoft must use some sort of 3rd party functionality for this.  You can do it in work via GUI but iti is not recorded in VBA workspace so not available via COM.

If someone finds a way to do this please reopen.
