### ISSUE TITLE
Error using Docto

### ISSUE THREAD

**Issue by Chris2Power** [tobya/DocTo#31]
I always get an Error with docto (new user).
Exiting with Error Code 220.
EConvertError '14.0' ist not a valid floating point value
Office 2010 ist installed. Can you give me a hint?

**Comment by tobya** [comment]
Hi

Can you give me an example command line you are using to run this.  I will see if I can track down what is causing the error.

**Comment by Chris2Power** [comment]
Hi, batch contains:

docto -f C:\docto-test\test.doc -O c:\docto-test\test.pdf -T wdFormatPDF -GL Logfile.log -L 10

output:
Log Level Set To:10
Loading Configuration...
Parameter Count is 10
Input File is: C:\docto-test\GODO Sonnhalde.doc
Output file is: C:\docto-test\GODO Sonnhalde.pdf
Log Level Set To:10
Type Integer is: 17
Ready to Execute
*******************************************
Error: EConvertError  '11.0' is not a valid floating point value C:\docto-test\G
ODO Sonnhalde.doc:C:\docto-test\GODO Sonnhalde.pdf
*******************************************
Error: Exiting with Error Code : 220

**Comment by tobya** [comment]
Are you somewhere in the world where you use ',' (comma) to seperate decimal numbers rather than a '.' (point)?

eg do you write 11,0 and 11,1 or 11.0 11.1

**Comment by tobya** [comment]
@Chris2Power  This issue is fixed now.  It was an internationlisation issue I think.  The latest relase

https://github.com/tobya/DocTo/releases/tag/V0.7.9

has the fix in it.
