### ISSUE TITLE
save to txt error

### ISSUE THREAD

**Issue by hungminhtran** [tobya/DocTo#32]
My word doc contents many unicode characters. I can't read it after convert to txt.

**Comment by hungminhtran** [comment]
https://msdn.microsoft.com/en-us/library/office/ff860880.aspx
Need a parameter for user to input the encoding

**Comment by tobya** [comment]
I'll see what i can do. Does using Unicode format help

> wdFormatUnicodeText

**Comment by hungminhtran** [comment]
Yes, I use it but still get wrong character encoding.
> wdFormatUnicodeText

**Comment by tobya** [comment]
Ok I will work on adding the encoding parameter as  a command line param to docto.

**Comment by tobya** [comment]
@hungminhtran would you be able to send me a document to try?

**Comment by tobya** [comment]
I have added in Encoding as  a parameter -E set to integer.

Not in master as I need you @hungminhtran to check it works.  Compiled version here https://github.com/tobya/DocTo/releases/tag/V0.7.10Fix

**Comment by hungminhtran** [comment]
@tobya 
I checked successfully with this doc below
[link doc](https://www.dropbox.com/s/redrdzxte8gqhjr/connguoi.doc?dl=0)
[wrong encoding](https://www.dropbox.com/s/2y6bohin537am0r/Screenshot%202016-05-08%2023.21.41.png?dl=0)
[right encoding](https://www.dropbox.com/s/ic0o5z8dx8qaxxp/Screenshot%202016-05-08%2023.21.59.png?dl=0)

command with args

>  wdFormatEncodedText -E  65001

**Comment by tobya** [comment]
Great, I'll push to master then.  I might use your linked doc for testing is that ok?  Do you mind if it is in github?

**Comment by hungminhtran** [comment]
It's okie, bro.
