### ISSUE TITLE
Error: Exiting with Error 400: EOleSysError Invalid class string, ProgID: "Word.Application"

### ISSUE THREAD

**Issue by tobya** [tobya/DocTo#35]
When word not installed.

Nice error message would be good.

**Comment by tobya** [comment]
This was fixed 


https://github.com/tobya/DocTo/blob/master/src/MainUtils.pas#L400

**Comment by dimasusl** [comment]
Release V0.8.14 

docto.exe -F test.rtf -O test.pdf -T wdFormatPDF
Exiting with Error 400: EOleSysError Недопустимая строка с указанием класса, ProgID: "Word.Application"
