### ISSUE TITLE
Directory conversion attempt fails on A: drive

### ISSUE THREAD

**Issue by hollasch** [tobya/DocTo#36]
- OS: Windows 10
- Docto Version:0.8.11
- Office Version : 16

Here's an example:
```
A:\srh\TEALS\apcsa-curriculum-2 > ..\apcsa-curriculum\tools\docto.exe -T wdFormatPDF -F "A:\srh\TEALS\apcsa-curriculum-2" -O "A:\srh\z" -OX .pdf
FileToConvert:A:\srh\TEALS\apcsa-curriculum-2
OutputFile:A:\srh\z\.pdf
Ext17
*******************************************
 (A:\srh\TEALS\apcsa-curriculum-2\) name isn't valid.
*******************************************
Error: Exiting with Error Code : 220
```

Note that the directory `A:\srh\z` exists and is empty. The directory specified to the `-F` argument exists, and is the current working directory, and contains `.docx` files.

Specifying `.` as the target directory yields a similar result:
```
A:\srh\TEALS\apcsa-curriculum-2 > ..\apcsa-curriculum\tools\docto.exe -T wdFormatPDF -F "." -O "A:\srh\z" -OX .pdf
FileToConvert:A:\srh\TEALS\apcsa-curriculum-2\.
OutputFile:A:\srh\z\.pdf
Ext17
*******************************************
 (A:\srh\TEALS\apcsa-curriculum-2\) name isn't valid.
*******************************************
Error: Exiting with Error Code : 220
```

**Comment by tobya** [comment]
@hollasch Thank you for the issue.  I wil have a look.

Can you try with a `\` on the end of the output dir  `A:\srh\TEALS\apcsa-curriculum-2\`

     ..\apcsa-curriculum\tools\docto.exe -T wdFormatPDF -F "A:\srh\TEALS\apcsa-curriculum-2\" -O "A:\srh\z" -OX .pdf

I have never tried using `.` so i'm not sure about that.

**Comment by tobya** [comment]
@hollasch  Actually I don't think that was the issue as it should be fixed.   Can you try on the `C:` drive?  Do you get the same error?

Are their .doc files or just .docx files in the directory?

**Comment by hollasch** [comment]
There are only `*.docx` files in the directory.

The command works as expected on the `C:` drive. It looks like the behavior is only on my `A:` drive. If I create a virtual `B:` drive, that seems to work fine as well.

In case it's something odd in your code with the letter itself, you can create a virtual `A:` drive with the following command:

```
subst A: C:\
```

**Comment by tobya** [comment]
I think you `./` issue is a bug with relative paths.  I have logged a seperate issue #38

**Comment by tobya** [comment]
@hollasch The latest release has a fix for the relative paths issue and the incorrect error output.   I havent done anything about the a: issue though.

**Comment by hollasch** [comment]
NOTE: The release binary is different, but still reports version 0.8.11.

**Comment by hollasch** [comment]
I think this is the same binary, as error messages in general still yield the carriage-return bug. Let me know when you get it sorted out and I'll re-test.

**Comment by tobya** [comment]
I will take a look.

**Comment by tobya** [comment]
@hollasch I have made a new release. Should be fine.  If not let me know exactly where the messed up error is occuring.  Thanks

**Comment by tobya** [comment]
I think this is now fixed.
