### ISSUE TITLE
Error output is malformed

### ISSUE THREAD

**Issue by hollasch** [tobya/DocTo#37]
While testing another issue (#36), I verified that the error output is malformed. See the line between the asterisks lines below. It looks like the file name is printed with only a carriage return, after which the error message itself is printed.

```
A:\srh\TEALS\x > tools\docto.exe -T wdFormatPDF -F "A:\srh\TEALS\x\" -O "A:\srh\z\" -OX .pdf
FileToConvert:A:\srh\TEALS\x\
OutputFile:A:\srh\z\.pdf
Ext17
*******************************************
 (A:\srh\TEALS\x\)on  The directory name isn't valid.
*******************************************
Error: Exiting with Error Code : 220
```

**Comment by tobya** [comment]
ahhh amazing.  I had noticed this bug a long time ago but never could figure out what was happening.  A bit of poking around with your suggestion and I think I've solved it, thank you @hollasch

**Comment by hollasch** [comment]
Verified fixed.
