### ISSUE TITLE
Relative paths fail

### ISSUE THREAD

**Issue by tobya** [tobya/DocTo#38]
Relative paths 

    ../mydocs/lookhere

will find and list all files but word will exit with an error.  

To fix the relative path needs to be turned into a absolute path prior to passing to word

Related to #22

**Comment by mlevison** [comment]
Perhaps you could add this to the documentation? I just spent a confusing 10 minutes proving that quite by accident.

**Comment by tobya** [comment]
Thanks.

Are you saying that this is still an  issue? 

Can you provide me with the Version number and the exact command line you used?

**Comment by mlevison** [comment]
DocTo Version:1.1.24.45.alpha
OfficeApp Version:16

Command line docto.exe --InputFile .\CSM\Material For Attendees\CSM Workbook.docx --OutputFile Staples\CSM

Error Message: *******************************************
Error: EOleException Sorry, we couldn't find your file. Was it moved, renamed, or deleted?-- ("C:\WINDOWS\...\CSM Workbook.docx")

----
When I made the first file absolute, but not the target directory - I got: 
FileToConvert:C:\Users\mark\Dropbox\1-APR\APR - Training Materials\CSM\Material For Attendees\CSM Workbook.docx
OutputFile:Staples\CSM\CSM Workbook.pdf
Ext17
*******************************************
Error: EOleException  The directory name isn't valid
*******************************************
Error: Exiting with Error Code : 220

---
If you want to see my inelegant powershell script I'm using - yell.

**Comment by tobya** [comment]
Great Thanks.  Always intrested to see a powershell script!

This was closed because I thought it was fixed.  Will look at it again.

**Comment by mlevison** [comment]
As it stands this script was designed to be run inside a particular folder. I think I may just pass in the folder as a param.

`# This script must be run inside the "/APR - Training Materials/"

"CSM", "CSPO", "A-CSM" | ForEach-Object {
    $sourceFolder = ".\" + $_ + "\Material For Attendees\"
    
    $sourceDocument = $sourceFolder + $_ + " Workbook.docx"
    Write-Output $sourceDocument
    # use of absolute documents is being forced on us by Word. Inelegant but we will live for now
    $absolutePathToFile = Resolve-Path -Path $sourceDocument
    Write-Output $absolutePathToFile

    $targetFolder = "Staples\" + $_
    Write-Output $targetFolder
    $absoluteTargetPath = Resolve-Path -Path $targetFolder

    docto.exe --InputFile $absolutePathToFile $absoluteTargetPath --format wdFormatPDF
}`

**Comment by tobya** [comment]
Thanks, I'll try and get to it as soon as I can.

**Comment by mlevison** [comment]
I wouldn't stress I've got a effective work around.

Cheers
Mark

**Comment by tobya** [comment]
@mlevison  This is now fixed.  So if you want to download the latest release 1.2 it should be sorted.  

If you want to fill in the use you or your company uses docto for, I would be grateful https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild
