### ISSUE TITLE
Conversion fails on Word .docx file for unknown reason

### ISSUE THREAD

**Issue by hollasch** [tobya/DocTo#40]
```
DocTo Version:0.8.11
OfficeApp Version:16
Source: http://github.com/tobya/DocTo/
```

(Using Office365 latest.)

Problem file: [Text Excel C Student Guide.docx](https://github.com/tobya/DocTo/files/926600/Text.Excel.C.Student.Guide.docx)

Conversion hangs when trying to process the above file. For some reason, it stalls for about five seconds, then brings up the Word save dialog. Hitting the save button seems to have no effect, as the dialog remains and the file is not saved. Note that Word has no issues with this file in a standard interactive session. I've tried removing all restrictions, removing all properties, upgrading to the latest version, even removing headers and footers. Nothing changes the conversion behavior.

Obviously, this has the simple workaround of removing the problem files (3/73 in my case) from the automated conversion workflow, but I'm filing this just for completeness.

**Comment by tobya** [comment]
@hollasch Thanks for the issue.  

In my use I have always had certain files that have for various reasons forced word to display dialogs which causes issues with a command line utility.  I have never really found a consistent reason for this.  However it is good to have a file to test on, thanks.  I'll see if I can track down or work around the issue.

**Comment by hollasch** [comment]
I think I've figured out the trigger. All three files that I have problems with have tables of contents. If you remove the table of contents from the Word file, then the conversion proceeds without issue. Also, once you cancel out of both dialogs, it looks like the PDF is still created, and looks good. The only annoying glitch is that the original dialog typically pops up under other windows, so it appears to hang, when it's really waiting for user input. You need to be ready for this, bring it forward, and then hit the escape key twice to dismiss the two dialogs.

**Comment by tobya** [comment]
@hollasch thanks for the additional info.  I will see if I can replicate and maybe try to deal with them, but there is not much I can do if Word is going to pop up modal windows.

**Comment by hollasch** [comment]
Totally agree. This isn't really a flaw in your tool, it's more about winword's behavior. Documenting here to help other users navigate this situation.

**Comment by tobya** [comment]
I have reproduced this and logged as #43

**Comment by tobya** [comment]
The next release will contain an experimental fix for this by using the 

    --skipdocswithtoc 

any docs with a TOC will be skipped, however I have found that some file would have been converted properly before but will now but skipped.  Any more info from anyone appreciated.
