### ISSUE TITLE
xlsTO convert XLSM

### ISSUE THREAD

**Issue by wadefl-yahoo** [tobya/DocTo#42]
Is it possible to convert XLSM with the program if so what steps do I need to take? So this seems to be just the Batch Folder mode, that does not convert the xlsm

Thanks, 
Wade

**Comment by tobya** [comment]
@wadefl-yahoo Thank you for the issue.

It seems to me that XLSM is

    xlOpenXMLWorkbookMacroEnabled=52

so try passing that in as the -T parameter.  If you are still having issues try to be as specific as possible about exactly what you are doing and what isnt working.  Please provide details of the command line you execute.

**Comment by tobya** [comment]
I will close this, but feel free to add more info if necessary.
