### ISSUE TITLE
Word Document with Tracked Changes causes DocTo to hang

### ISSUE THREAD

**Issue by pancodia** [tobya/DocTo#44]
Some of my docs have tracked changes. It seems that DocTo has problem to convert them.

**Comment by tobya** [comment]
@pancha0 Thanks for the heads up.  I will try to reproduce, we foudn the same issue with Tables of contents.

**Comment by tobya** [comment]
@pancodia Could you send me a document that causes this error?

**Comment by tobya** [comment]
I wonder would #93 fix this issue also?

**Comment by tobya** [comment]
I'm going to presume this is fixed, but feel free to reopen
