### ISSUE TITLE
Not working via Windows Task Scheduler

### ISSUE THREAD

**Issue by FVANCOP** [tobya/DocTo#46]
I want to use docto and xlsto via the Windows Task Scheduler but have some problems. 

In the folder C:\DOCXLS, the program DOCTO.EXE has been copied and the sample Word document "test.docx" has been created. Also the following 2 files have been created in that directory. 

Program 1 : c:\docxls\docto.bat

     "C:\docxls\docto" -f "C:\docxls\test.docx" -O "C:\docxls\result.txt" -T wdFormatText > C:\docxls\log.txt

Program 2 : C:\docxls\docto.vbs

     Dim WshShell
     Set WshShell = WScript.CreateObject("WScript.Shell")
     WshShell.Run """C:\docxls\docto.bat""", 0, True

- If I run the "docto.vbs" program from my common windows session, everything works has defined.
- If I run the "docto.vbs" from the windows task scheduler with my userid logged on, again no problem.
- If I run the "docto.vbs" from the windows task scheduler with another userid which is not logged on (attention : you have to check the field “Run with highest privileges”), I got following display in the log.txt file : 

     FileToConvert:C:\docxls\test.docx
     OutputFile:C:\docxls\result.txt
     Ext2
     *******************************************
     Error: EOleException  This command is not available because no document is open
     *******************************************
     Error: Exiting with Error Code : 220

**Comment by tobya** [comment]
@FVANCOP  Thanks for the issue.

hmmm this seems to me like a user rights issue.  If the user is not logged in there may be a problem with interacting with Word, which essentially is fundamentally designed to work within a user session so this may be causing it some issues.

To get more info, Try logging in as the user and see if you can run the vbs script from the logged in session - if not this should highlight potential user permission issues with the user.  if you can it will give us other information.

I will try to investigate, but in the meantime I suggest that if you can find a workaround, use that.

**Comment by FVANCOP** [comment]
Thanks for your answer and for your great job :-)

If I run it with my own userid, even if my user is not logged on, it works. So you are right : it is an access problem or a MSWord definition that is missing for the user that I use to perform the job.

It is not an access problem to the file - The user has access to it;
It is not an problem to access word (I logged that user on my PC and starts MSWindows for it without any problem).
Probably one of the special access... ; I have to check here with System Engineer what is missing.

Thanks a lot for your help. I will close the issue because it is not a problem of DOCTO.EXE.

**Comment by FVANCOP** [comment]
FYI : Problem solved

Resolution : I had to create the folder C:\Windows\System32\config\systemprofile\Desktop

see https://stackoverflow.com/questions/1674836/how-to-run-a-windows-2008-task-from-the-scheduler-with-interact-with-desktop
