### ISSUE TITLE
Option for Password Protected files

### ISSUE THREAD

**Issue by FVANCOP** [tobya/DocTo#47]
I have to treat lot of excel and word files with the DOCTO and XLSTO programs. I will do it via a generic program that will check all those files one bye one. This program will run has a background process without any intervention (via the Windows Task Scheduler).

If the word/excel file is password protected, you are prompted for the password.

It would be nice to have an option to bypass the prompt and just cancel the request when the document is password protected (and another option where you can specify the password of the file (if you know the password - which is not my case))

**Comment by tobya** [comment]
@FVANCOP  thank you for the feature request.  I will look at the word interfaces and see if there is a way I can do this.  I don't have any password protected files which is why it isnt implemented.

**Comment by tobya** [comment]
@FVANCOP I have fixed this to ignore password protected files.  When it encounters one it issues a log

     SKIPPED - Password Protected:D:\Development\GitHub\DocTo\test\Inputfiles\CullohillApplePie_Protected.doc

I have attached build in zip. Can you try and let me know if it solves your issue.  If it does I will release.

[docto.zip](https://github.com/tobya/DocTo/files/1254716/docto.zip)

**Comment by tobya** [comment]
@FVANCOP If you would like I would love to know what you are using DocTo for, you can add details on this wiki page  https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild

If you would rather not, no problem.

**Comment by tobya** [comment]
This is now fixed in 0.8.14

**Comment by FVANCOP** [comment]
It works for docto. Great thanks !

But .... can you do the same for XLSTO ?

**Comment by tobya** [comment]
@FVANCOP I've added this into the code now for Docto to also skip password protected XL files.  It will be available in next compiled release.
