### ISSUE TITLE
XLSTO with a fully qualified UNC path output name is not working

### ISSUE THREAD

**Issue by FVANCOP** [tobya/DocTo#49]
The command "XLSTO -f test.xls -O \\\\myserver\mysharedfolder\test.csv -T xlCSV " is not accepted  : the "-O" does not allow a fully qualified name (I mean "\\\\[server]\[map]\[output file]").

It is not a problem using it in the DOCTO command. Only in XLSTO.

<B>Example : </B>

<B>C:\converter>xlsto -f test.xlsx -o "\\\\gfs.pvgroup.intranet\gfs\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt" -T xlTextWindows -L 10</B>
Log Level Set To:10
Loading Configuration...
Parameter Count is 8
Input File is: test.xlsx
Output file is: \\\\gfs.pvgroup.intranet\gfs\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
Type Integer is: 20
Log Level Set To:10
Current Directory: C:\converter
Ready to Execute
\\\\gfs.pvgroup.intranet\gfs\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
\\\\gfs.pvgroup.intranet\gfs\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
FileToConvert:C:\converter\test.xlsx
OutputFile:\\\\gfs.pvgroup.intranet\gfs\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
Ext20
*******************************************
Error: EOleException  SaveAs method of Workbook class failed
*******************************************
Error: Exiting with Error Code : 220

<B>C:\converter>xlsto -f test.xlsx -o "G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt" -T xlTextWindows -L 10</B>
Log Level Set To:10
Loading Configuration...
Parameter Count is 8
Input File is: test.xlsx
Output file is: G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
Type Integer is: 20
Log Level Set To:10
Current Directory: C:\converter
Ready to Execute
G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
FileCreated: G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt
Creating File: G:\DPT\IT_D001\Infra_ZOS_DBA_D001S\03_Zseries\result.txt

**Comment by tobya** [comment]
hmm I'll take a look, this looks like it might be an excel issue though.  

Thanks for raising the issue.

**Comment by tobya** [comment]
This works with a workaround.  If you double up the `\\` at the begining it works

eg.

> Docto -XL -f test.xls -O \\\\myserver\mysharedfolder\test.csv -T xlCSV 

note the `\\\\` before myserver.
