### ISSUE TITLE
Html with base64 encoded image not showing image in docx

### ISSUE THREAD

**Issue by jimenabpose** [tobya/DocTo#52]
I'm using docto to convert html to docx, but when the html has a base64 encoded image it appears in the docx as an invalid image and it's not shown. Here you can find an example of the html input and the docx output: https://drive.google.com/drive/folders/0B1-JAAkA1WqjcWlVSVBvQnBOTzA?usp=sharing

**Comment by tobya** [comment]
Thanks for the issue

This may be an issue with word. Can you manually open the html page in word and see if you get the same result. Also check after saving. 

Let me know

**Comment by jimenabpose** [comment]
Thanks for the quick response.
Yes, it seems to be an issue with word, I can't see the image when I open the file as you described. Do you have any workaround?

**Comment by tobya** [comment]
I dont know of any workaround, sorry.

I'll close this issue as it is a problem with Word.
