### ISSUE TITLE
Raise File Save As dialog with some files

### ISSUE THREAD

**Issue by AdriedB** [tobya/DocTo#55]
Hi,

Converting some .doc files raises (after a successfull conversion) a "Save as dialog" with the possibility to save the Word document. In this way it isn't a commandline convert tool anymore.

Any help is preferred to solve this problem.

Regards,
Adrie

**Comment by tobya** [comment]
Hello, Thank you for the issue.

I'm not sure I follow. Do you wish for a save as dialog to pop up or are you saying one does?

If one pops up when it should not, can you provide the command line that you use to run docto and also if possible could you send me the document that is causing the problem?

There are lots of errors that can happen on documents that may cause such things to happen.  I'm not sure I can solve them all.  If you provide more information I can try.

**Comment by AdriedB** [comment]
Hi Tobya,

Thanks for you reaction. I have tried the following command-lines, but none is working.
(I am using docto version 0.8.14.24 and I am working with Word 2016) 

An example file is also attached.

docto -f GEOCADx.docx -O "GEOCADx.pdf" -T wdFormatPDF
docto -f "." -O "pdf" -T wdFormatPDF  -OX .pdf
docto -R true -f "GEOCADx.docx"  -T wdFormatPDF

[GEOCADx.docx](https://github.com/tobya/DocTo/files/1575219/GEOCADx.docx)

Hope you can help me.

Regards,
Adrie

**Comment by AdriedB** [comment]
I forgot the answer to the following question:

>>> I'm not sure I follow. Do you wish for a save as dialog to pop up or are you saying one does?

Of course I don not want a questionon a "Save as" dialog, because then I cannot use this tool to script the action to convert automatically doc/docx files to pdf.

**Comment by AdriedB** [comment]
Hi Tobya,

Best wishes for 2018 to start with!

>>> There are lots of errors that can happen on documents that may cause such things to happen. I'm not sure I can solve them all. If you provide more information I can try.

I am a little bit curious, can you provide me a status update? Can you help me to solve my problem?
Otherwise I have to find an other solution for converting word documents tot pdf.  

Kind regards,
Adrie

**Comment by tobya** [comment]
@AdriedB I'm not sure when I'll get to look at your document.  If I find a  simple solution I will let you know.  Perhaps for the moment if you have another solution that could provide you with a work around.

Thank you for trying out DocTo

**Comment by tobya** [comment]
This is solved in #59

**Comment by tobya** [comment]
Hello @AdriedB 

I think the latest release fixes this issue.

**Comment by AdriedB** [comment]
I'll try the latest release next week. Thanks for your support!

**Comment by AdriedB** [comment]
I have tested the latest version of docto and my problem with the Save As dialog is solved. Now I can use this tool to batch convert .doc(x) files to pdf. Again thanks for you support!
