### ISSUE TITLE
Error: EOleException: This command is not available because no documents have been opened

### ISSUE THREAD

**Issue by Ligadonasaude-gmcv** [tobya/DocTo#56]
Hi Tobya.

Man, I'm trying to execute the command through php. like this:

    exec('C:\wamp\www\DocTo-master\docto.exe -f C:\wamp\www\teste\\'.$filename.'.txt -O 
    "C:\wamp\www\ligadonasaude_pdfs\\'.$filename.'.pdf" -T wdFormatPDF 2>&1', $output, $return);

But when I do, this error happens. If I do it directly in the cmd, it works. Is that a bug or I'm doing something wrong?

Best!

**Comment by tobya** [comment]
Thanks for the issue.  It seems is not opening the file for some reason.  Can you print the string that gets put into exec() to see exactly what is being run?
