### ISSUE TITLE
Error: EOleException  This command is not available because no document is open

### ISSUE THREAD

**Issue by gavishwa** [tobya/DocTo#57]
Hi,
Am trying to convert the RTF to DOCX. It works flawless in command prompt. The same one doesnt work , if i give the command in Windows batch script. Am using Office 2010 word and OS is MS Win 2016 Standard  edition. Is this anything related with MS Windows-Distributed COM?

Kindly help me on the same.

Thanks,
--Vishwaa--

**Comment by tobya** [comment]
Hi  Thanks for the issue.

Can you provide the command line that works and your batch script that doesnt work?
Are you converting just one file or many?
Does the error happen on all files or just particular ones?
How are you using distributed COM?

**Comment by gavishwa** [comment]
Hi,

Working command:
=============
C:\Python27>docto -F "XXXXReleaseNotes_x01.rtf" -O "11.docx" -T 16
FileCreated: C:\Python27\11.docx

Not working one:
==========
cd /d C:\Jenkins\workspace\Test\PayLoad\XXXX_SW_Drop
rename XXXXReleaseNotes_GU_x00.rtf GU00.rtf
c:\doc2\docto.exe -F "GU00.rtf" -O "XXXXlV.docx" -T 16

Am converting only one file . It happens for all RTF. Am using Jenkins Framework which in turn has Distributed COM.

Thanks,
--Vishwaa--

**Comment by tobya** [comment]
Try using fully qualified filename for -F and -O and see if that fixes the issue?  

There are some issues with relative filenames.

**Comment by tobya** [comment]
I assume using a fully qualified filename worked?  @gavishwa 

I'll close this.

**Comment by Daherr20** [comment]
Hi, 

We are having problems when invoking docto.exe from IIS application which is hosted in 'Windows Server2019 Datacenter'. 

Office version: Microsoft Office Professional Plus 2016 (16.0.4266.1001)

Error: EOleException This command is not available because no document is open.

Can you please assist?

**Comment by tobya** [comment]
Hi @Daherr20 , did you try the solution above, it may work for you?
