### ISSUE TITLE
-R doesn't work

### ISSUE THREAD

**Issue by SirElismyer** [tobya/DocTo#66]
Simple as that. the -R option doesn't work at all.

Latest version.
Windows 10
.doc to .pdf using the command provided in the readme

**Comment by tobya** [comment]
Thank you for the issue. I'll take a look and see if I can reproduce.

**Comment by tobya** [comment]
@SirElismyer  I investigated this, it does work but you need to add `true` after -R

    docto.exe -f "inputfile.doc" -o "outputfile.pdf"  -R true

I agree this is not obvious from the readme (and I even forgot myself you needed todo this, so I will add to readme and also add to log when no value provided.

Thank you for using docto.
