### ISSUE TITLE
XlsTo - convert only first page or one named table not whole spreadsheet

### ISSUE THREAD

**Issue by gamgamstyle** [tobya/DocTo#67]
Is it possible to convert only first page (or number given) or a named table not the whole spreadsheet?

**Comment by tobya** [comment]
Thank you for the issue @gamgamstyle .

Currently that is not possible. I'll add it as a feature request.  I am unsure when it will be implemented.

If you or someone else would like to submit a PR that would be great.

**Comment by tobya** [comment]
You can now output to pdf certain pages using these parameters

> --PDF-FromPage
          Save a range of pages to pdf. Integer/String. If integer --PDF-ToPage must also be set.
          Other values wdExportCurrentPage, wdExportSelection
      --PDF-ToPage
          Save a range of pages to pdf. Integer. --PDF-FromPage must also be set.

**Comment by gamgamstyle** [comment]
Thank you very much.

**Comment by tobya** [comment]
Available in latest release just up now.
