### ISSUE TITLE
Tutorial PLEASE (step by step) Convert Word to TXT

### ISSUE THREAD

**Issue by me-suzy** [tobya/DocTo#69]
hello, I have many .doc and .docx files and I want to convert into .txt. I believe I had to use cmd platform,. For example, where should I use this line: ?

docto -f C:\Directory\MyFile.doc -O "C:\Output Directory\MyTextFile.txt" -T wdFormatText 

I open cmd, try, comamnd isn't good. I open testDocTo.bat and automatically carries out some rows then closes. So, how can I use your program?

**Comment by tobya** [comment]
If DocTo is not on your path you will need to supply the full path so try

> "c:\path\to\docto.exe" -f C:\Directory\MyFile.doc -O "C:\Output Directory\MyTextFile.txt" -T wdFormatText

**Comment by me-suzy** [comment]
hello. Yes, but where is the file doctor.exe in your archive software? I download DocTo-master.zip and I cannot find any .exe ??

**Comment by tobya** [comment]
Hi, You have downloaded the source code.  

You can download the `.exe` from the [releases page](https://github.com/tobya/DocTo/releases)  Here you can directly download `docto.exe`
