### ISSUE TITLE
Running under Wine?

### ISSUE THREAD

**Issue by shakenbakesl** [tobya/DocTo#70]
Hi, has anyone tested running this application under Wine? At the moment I'm converting docx to pdf via xfvb -> wine -> winword + macro + cups-pdf but the process is a bit convoluted and could be a lot better. I'd like to give this a try. Does anyone have any millage using it this way?

**Comment by shakenbakesl** [comment]
If anyone's interested, I tried it and it works fine. My setup is based around the popular ubuntu/wine/office 2010 configuration that people will invariably come across if they're doing this. It's significantly quicker than the method I've currently being using.  The only quirk I've noticed is that the -f and -O arguments will not take spaces no matter what I've tried.

**Comment by tobya** [comment]
@shakenbakesl  Thanks for the update.

If you felt like writing a [Wiki page](https://github.com/tobya/DocTo/wiki) on how to set up on Wine that would be great.  Also if you wanted you could update[ this page](https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild) on what you are using DocTo for.
