### ISSUE TITLE
V0.8.17 - DocTo Blocked in my antivirus program due to being potentially untwanted

### ISSUE THREAD

**Issue by elektrotiko** [tobya/DocTo#71]
V0.8.17 - DocTo is being totally blocked by my F-secure, while V0.8.15 is accepted. What changes have been made in V0.8.17 ?

**Comment by tobya** [comment]
Hello

The main changed introduced would have been the ability to call https urls with the -w param.

This would have added quite a bit of size to the exe as it brings in lots of code used to deal with this.  Everything else is minor bug fixes.
