### ISSUE TITLE
Does this tools support math formulas?

### ISSUE THREAD

**Issue by LittleNewton** [tobya/DocTo#73]
I wrote some math formualtions using the MS-Word's built-in tool in a **.docx** file.

I can use **DocTo** to convert this docx to .txt file and all the formulas are in LaTeX format in the texts. It was pretty nice.

But when I tried to translate it into .pdf file, it doesn't work as I wished since the generated PDF was blank.

This is the Word file outline:

<img width="891" alt="屏幕快照 2019-04-11 17 20 15" src="https://user-images.githubusercontent.com/17793356/55945829-218c7a80-5c7e-11e9-9d1d-988a828f094e.png">

This is the txt file.

`G=\mathbb{Z}_{p^k}=,a.，b\in G，S_2=\left\{a,\ a^{-1},\ b,\ b^{-1}\right\}，
求证：\mathrm{\Gamma}=\mathbf{Aut}\left(Cayley\left(G,\ S_2\right)\right)\cong G\rtimes\mathbb{Z}_4
//\ 对于某个v\in V\left(Cayley\left(G,\ S_2\right)\right)，如下定义\mathrm{\Gamma}_v:=\left\{g\middle| g\in\mathrm{\Gamma},\ v^g=v\right\}
//\ 对于克莱因四元群，\mathrm{\Gamma}_{middle_point}=\left\{\alpha_1,\ \alpha_2,\ \alpha_3,\ \alpha_4\right\}
 G\trianglelefteq\mathrm{\Gamma}
 \mathrm{\Gamma}_v\cong\mathbb{Z}_4
`

And this is the blank pdf:
(It is empty so I think it neccessory to put a picture here.)

**Comment by tobya** [comment]
Thanks for the issue.

The code just asks Word to convert to PDF, so if its not working its an issue with Word. 

What happens if you save as pdf from within word manually?

Can you provide the commandline you are running?
