### ISSUE TITLE
"Exiting with Error Code : 220" and default program

### ISSUE THREAD

**Issue by lboullu** [tobya/DocTo#78]
When I run "docto -f "C:\Dir with Spaces\FilesToConvert\" -O "C:\DirToOutput" -T wdFormatPDF  -OX .pdf" in a folder full of docX, I get a box telling me "Word is not the default program for this kind of file, do you want to set it default?" and no matter what I answer I get the message 
> Ext17
> *******************************************
> Error: EOleSysError 
> *******************************************
> Error: Exiting with Error Code : 220

In the settings I set Word to be the default program for .doc, .docx, .docxml, .dot, .dothtml and .dotm, am I missing something?

Thanks

**Comment by tobya** [comment]
Thanks for the issue.

Perhaps try using -fx to specify '.docx' or 'docx' and see if that works.

Also try using docto to convert a single file specified file and see if that works

**Comment by lboullu** [comment]
Ok it's working now, maybe restarting my computer helped or something

Thanks for your great tool!
