### ISSUE TITLE
Export word bookmarks

### ISSUE THREAD

**Issue by DrrMrr** [tobya/DocTo#79]
Hi,

is it possible to export also bookmarks when pdf is generated from docx file? 

Thank you and best regards
Damjan

**Comment by tobya** [comment]
Hello Thank you for the feature request.  I am unsure.  Perhaps their might be a way to export bookmarks.

Do you want them as links in the pdf or what do you mean by export?

**Comment by DrrMrr** [comment]
Hi,

Maybe I didn't explain correctly. Just to have an option to generate bookmarks.

This is Adobe reference pdf with bookmarks as seen on picture below:
https://helpx.adobe.com/pdf/acrobat_reference.pdf

![image](https://user-images.githubusercontent.com/174676/67847718-9aaccb80-fb03-11e9-8be8-82c27d6f93d8.png)

That would be just perfect, even though the app is awesome without that.

Best regards
Damjan

**Comment by tobya** [comment]
Thanks for the update.

Could you let me know what you need to do in a word document (via the UI) to get it to export bookmarks in a created pdf.  Once I have that information I can figure out how to get docto to export to the pdf also.

**Comment by DrrMrr** [comment]
There is an aoption when you choose export pdf:
https://superuser.com/questions/95222/from-word-to-pdf-including-bookmarks#118531

**Comment by tobya** [comment]
Great - that is really helpful.

I will see what I can do.

**Comment by tobya** [comment]
ActiveDocument.ExportAsFixedFormat OutputFileName:= _
        "D:\DocumentsFolder\Documents\sasfasfsadf.pdf", ExportFormat:= _
        wdExportFormatPDF, OpenAfterExport:=True, OptimizeFor:= _
        wdExportOptimizeForPrint, Range:=wdExportAllDocument, From:=1, To:=1, _
        Item:=wdExportDocumentContent, IncludeDocProps:=True, KeepIRM:=True, _
        CreateBookmarks:=wdExportCreateHeadingBookmarks, DocStructureTags:=True, _
        BitmapMissingFonts:=True, UseISO19005_1:=False

**Comment by tobya** [comment]
I guess this could be the default?  Is there any reason anyone would not want bookmarks?

**Comment by DrrMrr** [comment]
I also think so. I don't see the problem if this is by default or only this option is available.

**Comment by tobya** [comment]
I have this working I'll try and push a PR over the weekend.

**Comment by tobya** [comment]
Hi @DrrMrr I have implemented this now and released.  

Let me know how you get on and if you have any issues.  Also would be delighted if you could fill in your usecase here https://github.com/tobya/DocTo/wiki/Uses-of-DocTo-in-the-wild

**Comment by DrrMrr** [comment]
Hi @tobya , I will try new features in the coming week. I can also post usecase as you have described. I will let you know how it will go.
