### ISSUE TITLE
Problems when running in service - run from commandline no problem

### ISSUE THREAD

**Issue by uaiuai** [tobya/DocTo#81]
Hello I am trying to use docto to convert doc files in a server process.
However it fails when running in the process - I can see how word is started and starts to use more and more ram but will never create the PDF (20191128 14:57:19). However if start from the commandline (20191128 14:58:32)  with the same command it behaves as it should. I tried to run the Service as system as well as with my user account.
The commandline I run is 

> c:\PTC\docto\docto.exe -F "C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\work\input" -O "C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\work\output" -T wdFormatPDF -GL "C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\job.log" -X false 

this is the logfile:

````
[20191128 14:57:19 -]: FileToConvert:C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\work\input\20522-9-0952_07_DOC_PUBLIC5737573602012175316.doc
OutputFile:C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\work\output\\20522-9-0952_07_DOC_PUBLIC5737573602012175316
Ext17
*******************************************
Error: EOleException  This command is not available because no document is open

[20191128 14:58:32 -]: FileCreated: C:\Temp\JobServerData\JobServer Files\2e5fce5a-722d-4714-adba-87ea2d7b0b60\work\output\\20522-9-0952_07_DOC_PUBLIC5737573602012175316
`````
[2e5fce5a-722d-4714-adba-87ea2d7b0b60.zip](https://github.com/tobya/DocTo/files/3902110/2e5fce5a-722d-4714-adba-87ea2d7b0b60.zip)

**Comment by tobya** [comment]
Hi

What version are you using?  Docto -V

Why is it listing .zip as the filename?

**Comment by tobya** [comment]
Can you run with Verbose logging and see if it gives any more info.  Add `-L 10` to your commandline to get more logging.

**Comment by uaiuai** [comment]
Unofrtunately not much more Info. Winword starts to use all CPU of one core and then memory consumption of winword.exe rises until the system hangs.

Log Level Set To:10
File List
C:\Temp\JobServerData\JobServer Files\8ad2a665-02da-4201-b74c-4764d78543f8\work\input\20522-9-0952_07_DOC_PUBLIC1533772221115647312.doc

Current Directory: C:\Temp\JobServerData\JobServer Files\8ad2a665-02da-4201-b74c-4764d78543f8\work\input
Ready to Execute
ExecuteConversion:C:\Temp\JobServerData\JobServer Files\8ad2a665-02da-4201-b74c-4764d78543f8\work\input\20522-9-0952_07_DOC_PUBLIC1533772221115647312.doc
WordVersion:16.0
WordVersion Major:16
Version >= 14 Using Saveas2 Function
FileToConvert:C:\Temp\JobServerData\JobServer Files\8ad2a665-02da-4201-b74c-4764d78543f8\work\input\20522-9-0952_07_DOC_PUBLIC1533772221115647312.doc
OutputFile:C:\Temp\JobServerData\JobServer Files\8ad2a665-02da-4201-b74c-4764d78543f8\work\output\\20522-9-0952_07_DOC_PUBLIC1533772221115647312
Ext17
*******************************************
Error: EOleException  This command is not available because no document is open

**Comment by tobya** [comment]
I have had similar problems before with windows.  Take a look at #57  to see if the solutions offered in the thread will work for you.  It seems possibly to be a windows issue.

**Comment by uaiuai** [comment]
Thanks that helped, the proposed solution from #46 and #57 works like a charm
