### ISSUE TITLE
Creation of PDF leads to a save-changes question

### ISSUE THREAD

**Issue by Wolle181** [tobya/DocTo#93]
When a document containing a table of content (or other dynamic content like picture lists etc) is converted into a PDF, WORD usually updates the source document prior to store it as PDF.

When leaving WORD (respectively closing the reference) it will issue a save-changes dialog to the UI. In unattended sessions, this will stop the process or result in remaining instances of WORD in the background.

The installed WORD-Version is Office 2016 (not Office 365), German Edition. 

This should be turned off or made configurable.

[Reason: For the OutputFileFormat 17, the code does not reach the line WordApp.ActiveDocument.Close(wdDoNotSaveChanges). ]

**Comment by tobya** [comment]
Thank you for the issue.

This is a problem. However I’m not sure what the fix is? Do you know what needs to be turned off?

**Comment by tobya** [comment]
Ohh I see you’ve submitted a pr, I’ll take a look. Thanks for the contributions

**Comment by tobya** [comment]
Relates to PR #95
